/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"

#include "StdH.h"
#include "ModelsMP/Enemies/AirElemental/AirElemental.h"
#include "ModelsMP/Enemies/AirElemental/Elemental.h"
#include "Models/Enemies/Elementals/Twister.h"

#include <EntitiesMP/AirElemental.h>
#include <EntitiesMP/AirElemental_tables.h>
CEntityEvent *EElementalGrow::MakeCopy(void) { CEntityEvent *peeCopy = new EElementalGrow(*this); return peeCopy;}
EElementalGrow::EElementalGrow() : CEntityEvent(EVENTCODE_EElementalGrow) {;
};
#line 16 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"

#define ECF_AIR ( \
  ((ECBI_BRUSH|ECBI_MODEL|ECBI_CORPSE|ECBI_ITEM|ECBI_PROJECTILE_MAGIC|ECBI_PROJECTILE_SOLID)<<ECB_TEST) |\
  ((ECBI_MODEL|ECBI_CORPSE|ECBI_ITEM|ECBI_PROJECTILE_MAGIC|ECBI_PROJECTILE_SOLID)<<ECB_PASS) |\
  ((ECBI_MODEL)<<ECB_IS))

#define AIRBOSS_EYES_HEIGHT 1.7f
#define AIRBOSS_BODY_HEIGHT 1.0f

// info structure
static EntityInfo eiAirElemental = {
  EIBT_AIR, 1500.0f,
  0.0f, AIRBOSS_EYES_HEIGHT, 0.0f,
  0.0f, AIRBOSS_BODY_HEIGHT, 0.0f,
};

#define RAND_05 (FLOAT(rand())/RAND_MAX-0.5f)
#define FIREPOS_TWISTER FLOAT3D(-0.04f, 0.91f, -1.06f)
#define SIZE_NORMAL 1
#define SIZE_BIG01  2
#define SIZE_BIG02  3
#define SIZE_BIG03  4

#define AIRBOSS_MAX_TA 10
#define AIRBOSS_MAX_GA 3

FLOAT afTriggerArray[AIRBOSS_MAX_TA] = { 0.9f, 0.8f, 0.7f, 0.6f, 0.5f,
                                         0.4f, 0.3f, 0.2f, 0.1f, 0.05f };
FLOAT afGrowArray[AIRBOSS_MAX_GA][2] = { 0.8f, 25.0f,
                                         0.6f, 50.0f,
                                         0.4f, 100.0f };

void CAirElemental::SetDefaultProperties(void) {
  m_bFloat = FALSE ;
  m_fAttPosY = 0.0f;
  m_bInitialAnim = FALSE ;
  m_penTrigger01 = NULL;
  m_penTrigger02 = NULL;
  m_penTrigger03 = NULL;
  m_penTrigger04 = NULL;
  m_penTrigger05 = NULL;
  m_penTrigger06 = NULL;
  m_penTrigger07 = NULL;
  m_penTrigger08 = NULL;
  m_penTrigger09 = NULL;
  m_penTrigger10 = NULL;
  m_fAttSizeCurrent = 0.0f;
  m_fAttSizeBegin = 12.5f;
  m_fAttSizeEnd = 100.0f;
  m_fAttSizeRequested = 0.0f;
  m_bAttGrow = FALSE ;
  m_iSize = 0;
  m_fLastSize = 0.0f;
  m_fTargetSize = 0.0f;
  m_fGrowSpeed = 2.0f;
  m_tmWindNextFire = 0.0f;
  m_fWindFireTimeMin = 10.0f;
  m_fWindFireTimeMax = 20.0f;
  m_iWind = 0;
  m_bDying = FALSE ;
  m_tmDeath = 1e6f;
  m_fDeathDuration = 0.0f;
  m_fWindBlastFirePosBegin = FLOAT3D(- 0.44f , 0.7f , - 0.94f);
  m_fWindBlastFirePosEnd = FLOAT3D(0.64f , 0.37f , - 0.52f);
  m_tmLastAnimation = 0.0f;
  m_penDeathInflictor = NULL;
  m_bRenderParticles = FALSE ;
  m_soFire.SetOwner(this);
m_soFire.Stop_internal();
  m_soVoice.SetOwner(this);
m_soVoice.Stop_internal();
  m_colParticles = COLOR(C_WHITE  | CT_OPAQUE );
  CEnemyBase::SetDefaultProperties();
}
  
#line 135 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::Read_t(CTStream * istr) 
#line 136 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 137 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CEnemyBase  :: Read_t  (istr );
#line 138 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_emEmiter  . Read_t  (* istr );
#line 139 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 141 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::Write_t(CTStream * istr) 
#line 142 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 143 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CEnemyBase  :: Write_t  (istr );
#line 144 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_emEmiter  . Write_t  (* istr );
#line 145 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  CTString CAirElemental::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 157 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 158 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CTString str ;
#line 159 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
str  . PrintF  (TRANS  ("%s was -*blown away*- by an Air Elemental") , strPlayerName );
#line 160 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return str ;
#line 161 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  const CTFileName & CAirElemental::GetComputerMessageName(void)const {
#line 163 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
static DECLARE_CTFILENAME  (fnm  , "DataMP\\Messages\\Enemies\\AirElemental.txt");
#line 164 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return fnm ;
#line 165 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 167 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::Precache(void) 
#line 168 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 169 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CEnemyBase  :: Precache  ();
#line 171 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheClass  (CLASS_TWISTER );
#line 172 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheClass  (CLASS_BLOOD_SPRAY );
#line 173 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_AIRELEMENTAL_WIND );
#line 175 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheModel  (MODEL_INVISIBLE );
#line 176 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheModel  (MODEL_ELEMENTAL );
#line 178 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheTexture  (TEXTURE_ELEMENTAL );
#line 180 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheSound  (SOUND_FIREWINDBLAST );
#line 181 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheSound  (SOUND_FIRETWISTER );
#line 182 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheSound  (SOUND_ROAR );
#line 183 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheSound  (SOUND_DEATH );
#line 184 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrecacheSound  (SOUND_EXPLOSION );
#line 185 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 188 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void * CAirElemental::GetEntityInfo(void) {
#line 189 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return & eiAirElemental ;
#line 190 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 193 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CModelObject * CAirElemental::ElementalModel(void) {
#line 194 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CAttachmentModelObject  & amo0  = * GetModelObject  () -> GetAttachmentModel  (AIRELEMENTAL_ATTACHMENT_BODY );
#line 195 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return & (amo0  . amo_moModelObject );
#line 196 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 199 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 200 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 201 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 203 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(m_bInitialAnim ){return ;}
#line 206 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fHealth  = GetHealth  ();
#line 207 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fFullDamage  = fDamageAmmount  * DamageStrength  (((EntityInfo  *) GetEntityInfo  ()) -> Eeibt  , dmtType ) * GetGameDamageMultiplier  ();
#line 208 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(m_bAttGrow  && m_iSize  < 2){
#line 209 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(fHealth  - fFullDamage  < afGrowArray  [ m_iSize  + 1 ] [ 0 ] * m_fMaxHealth ){
#line 210 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 211 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetHealth  (fHealth );
#line 212 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return ;
#line 213 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 214 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}else if(m_bAttGrow  && m_iSize  == 2){
#line 215 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(fHealth  - fFullDamage  < 1.0f){
#line 216 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 217 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetHealth  (fHealth );
#line 218 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return ;
#line 219 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 220 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 224 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(IsOfClass  (penInflictor  , "AirElemental")){
#line 225 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return ;
#line 226 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 229 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(dmtType  == DMT_TELEPORT )
#line 230 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 231 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return ;
#line 232 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 235 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(dmtType  == DMT_CLOSERANGE  || 
#line 236 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
dmtType  == DMT_BULLET  || 
#line 237 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
dmtType  == DMT_IMPACT  || 
#line 238 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
dmtType  == DMT_CHAINSAW )
#line 239 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 240 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return ;
#line 241 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 244 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(dmtType  == DMT_CANNONBALL )
#line 245 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 246 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
fDamageAmmount  *= 0.6f;
#line 247 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 249 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fOldHealth  = GetHealth  ();
#line 250 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 251 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fNewHealth  = GetHealth  ();
#line 253 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CEntityPointer * penTrigger  = & m_penTrigger01 ;
#line 255 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
for(INDEX i  = 0;i  < AIRBOSS_MAX_TA ;i  ++){
#line 256 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fHealth  = afTriggerArray  [ i  ] * m_fMaxHealth ;
#line 258 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(fHealth  <= fOldHealth  && fHealth  > fNewHealth )
#line 259 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 260 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(& * penTrigger  [ i  ]){
#line 261 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SendToTarget  (& * penTrigger  [ i  ] , EET_TRIGGER  , FixupCausedToPlayer  (this  , m_penEnemy ));
#line 262 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 263 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 264 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 266 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
for(i  = 0;i  < AIRBOSS_MAX_GA ;i  ++){
#line 267 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fHealth  = afGrowArray  [ i  ] [ 0 ] * m_fMaxHealth ;
#line 269 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(fHealth  <= fOldHealth  && fHealth  > fNewHealth )
#line 270 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 271 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fAttSizeRequested  = afGrowArray  [ i  ] [ 1 ];
#line 272 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_iSize  = i ;
#line 273 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
EElementalGrow  eeg ;
#line 274 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SendEvent  (eeg );
#line 275 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 276 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 279 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_colBurning  = COLOR (C_WHITE  | CT_OPAQUE );
#line 281 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 284 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
INDEX CAirElemental::AnimForDamage(FLOAT fDamage) {
#line 285 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
INDEX iAnim  = ELEMENTAL_ANIM_IDLE ;
#line 286 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (iAnim  , 0);
#line 287 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return iAnim ;
#line 288 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 290 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::StandingAnimFight(void) {
#line 291 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_IDLE  , AOF_LOOPING  | AOF_NORESTART );
#line 292 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 295 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::StandingAnim(void) {
#line 296 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_IDLE  , AOF_LOOPING  | AOF_NORESTART );
#line 297 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 299 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::WalkingAnim(void) 
#line 300 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 301 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_IDLE  , AOF_LOOPING  | AOF_NORESTART );
#line 302 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 304 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::RunningAnim(void) 
#line 305 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 306 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
WalkingAnim  ();
#line 307 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 309 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::RotatingAnim(void) {
#line 310 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
WalkingAnim  ();
#line 311 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 313 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
INDEX CAirElemental::AnimForDeath(void) 
#line 314 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 315 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
INDEX iAnim ;
#line 316 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
iAnim  = ELEMENTAL_ANIM_IDLE ;
#line 317 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (iAnim  , 0);
#line 318 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return iAnim ;
#line 319 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 322 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::IdleSound(void) {
#line 324 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 325 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::WoundSound(void) {
#line 327 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 329 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::SizeModel(void) 
#line 330 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 331 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return ;
#line 332 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 335 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
BOOL CAirElemental::AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient) {
#line 336 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return CMovableModelEntity  :: AdjustShadingParameters  (vLightDirection  , colLight  , colAmbient );
#line 337 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 344 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::BlowUp(void) {
#line 360 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 364 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::EnemyPostInit(void) 
#line 365 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 366 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_soFire  . Set3DParameters  (600.0f , 150.0f , 2.0f , 1.0f);
#line 367 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_soVoice  . Set3DParameters  (600.0f , 150.0f , 2.0f , 1.0f);
#line 368 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_soSound  . Set3DParameters  (600.0f , 150.0f , 2.0f , 1.0f);
#line 369 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 371 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::LaunchTwister(FLOAT3D vEnemyOffset) 
#line 372 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 374 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT3D vFirePos  = FIREPOS_TWISTER  * m_fAttSizeCurrent  * GetRotationMatrix  ();
#line 375 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT3D vShooting  = GetPlacement  () . pl_PositionVector  + vFirePos ;
#line 376 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT3D vTarget  = m_penEnemy  -> GetPlacement  () . pl_PositionVector ;
#line 377 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fLaunchSpeed ;
#line 378 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fRelativeHdg ;
#line 381 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
EntityInfo  * peiTarget  = (EntityInfo  *) (m_penEnemy  -> GetEntityInfo  ());
#line 384 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vTarget  += vEnemyOffset ;
#line 386 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CPlacement3D pl ;
#line 387 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CalculateAngularLaunchParams  (vShooting  , peiTarget  -> vTargetCenter  [ 1 ] - 6.0f / 3.0f , 
#line 388 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vTarget  , FLOAT3D (0.0f , 0.0f , 0.0f) , 0.0f , fLaunchSpeed  , fRelativeHdg );
#line 390 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PrepareFreeFlyingProjectile  (pl  , vTarget  , vFirePos  , ANGLE3D (fRelativeHdg  , 0.0f , 0.0f));
#line 392 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ETwister  et ;
#line 393 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CEntityPointer penTwister  = CreateEntity  (pl  , CLASS_TWISTER );
#line 394 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
et  . penOwner  = this ;
#line 396 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
et  . fSize  = FRnd  () * 10.0f + m_fAttSizeCurrent  / 5.0f + 3.0f;
#line 397 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
et  . fDuration  = 15.0f + FRnd  () + 5.0f;
#line 398 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
et  . sgnSpinDir  = (INDEX) (Sgn  (FRnd  () - 0.5f));
#line 399 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
et  . bGrow  = TRUE ;
#line 400 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
et  . bMovingAllowed  = TRUE ;
#line 401 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
penTwister  -> Initialize  (et );
#line 403 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
((CMovableEntity  &) * penTwister ) . LaunchAsFreeProjectile  (FLOAT3D (0.0f , 0.0f , - fLaunchSpeed ) , (CMovableEntity  *) (CEntity  *) this );
#line 404 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 406 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::PreMoving() {
#line 429 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CEnemyBase  :: PreMoving  ();
#line 430 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 432 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::GetAirElementalAttachmentData(INDEX iAttachment,FLOATmatrix3D & mRot,FLOAT3D & vPos) 
#line 433 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 434 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
MakeRotationMatrixFast  (mRot  , ANGLE3D (0.0f , 0.0f , 0.0f));
#line 435 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vPos  = FLOAT3D (0.0f , 0.0f , 0.0f);
#line 436 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
GetModelObject  () -> GetAttachmentTransformations  (AIRELEMENTAL_ATTACHMENT_BODY  , mRot  , vPos  , FALSE );
#line 438 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CAttachmentModelObject  * pamo  = GetModelObject  () -> GetAttachmentModel  (AIRELEMENTAL_ATTACHMENT_BODY );
#line 439 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
pamo  -> amo_moModelObject  . GetAttachmentTransformations  (iAttachment  , mRot  , vPos  , TRUE );
#line 440 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vPos  = GetPlacement  () . pl_PositionVector  + vPos  * GetRotationMatrix  ();
#line 441 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 443 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT CAirElemental::GetCurrentStretchRatio(void) 
#line 444 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 445 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CAttachmentModelObject  & amo  = * GetModelObject  () -> GetAttachmentModel  (AIRELEMENTAL_ATTACHMENT_BODY );
#line 446 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fCurrentStretch  = amo  . amo_moModelObject  . mo_Stretch  (1);
#line 447 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fStretch  = (fCurrentStretch  - m_fAttSizeBegin ) / (m_fAttSizeEnd  - m_fAttSizeBegin );
#line 448 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return fStretch ;
#line 449 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
  
#line 451 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
void CAirElemental::RenderParticles(void) 
#line 452 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 453 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
static TIME  tmLastGrowTime  = 0.0f;
#line 455 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(m_bFloat ){
#line 456 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fTime  = _pTimer  -> GetLerpedCurrentTick  ();
#line 457 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CAttachmentModelObject  & amo0  = * GetModelObject  () -> GetAttachmentModel  (AIRELEMENTAL_ATTACHMENT_BODY );
#line 458 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
amo0  . amo_plRelative  . pl_PositionVector  (2) = m_fAttPosY  + pow  (sin  (fTime  * 2.0f) , 2.0f) * m_fAttSizeCurrent  * 2.0f / m_fAttSizeBegin ;
#line 459 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 460 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(m_bAttGrow ){
#line 461 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fSize  = Lerp  (m_fLastSize  , m_fTargetSize  , _pTimer  -> GetLerpFactor  ());
#line 462 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> StretchModel  (FLOAT3D (fSize  , fSize  , fSize ));
#line 463 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 465 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(m_bRenderParticles )
#line 466 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
#line 467 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fStretchRatio  = GetCurrentStretchRatio  ();
#line 468 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fStretch  = 1.0f + (fStretchRatio ) * 6.0f;
#line 469 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Particles_AirElemental  (this  , fStretch  , 1.0f , m_tmDeath  , m_colParticles );
#line 470 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 471 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
BOOL CAirElemental::
#line 476 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Die(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CAirElemental_Die
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EDeath, "CAirElemental::Die expects 'EDeath' as input!");  const EDeath &eDeath = (const EDeath &)__eeInput;
#line 478 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetDesiredRotation  (ANGLE3D (0.0f , 0.0f , 0.0f));
#line 479 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PlaySound  (m_soFire  , SOUND_DEATH  , SOF_3D );
#line 480 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_DEATH  , AOF_NORESTART );
#line 481 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_tmDeath  = _pTimer  -> CurrentTick  () + ElementalModel  () -> GetAnimLength  (ELEMENTAL_ANIM_DEATH );
#line 482 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bFloat  = FALSE ;
#line 483 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(ElementalModel  () -> GetAnimLength  (ELEMENTAL_ANIM_DEATH ) - 0.1f);
Jump(STATE_CURRENT, 0x015b0002, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b0002_Die_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0002
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b0003, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b0003_Die_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0003
;
#line 485 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PlaySound  (m_soVoice  , SOUND_EXPLOSION  , SOF_3D );
#line 486 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bDying  = TRUE ;
#line 487 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fDeathDuration  = 4.0f;
#line 489 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(m_fDeathDuration );
Jump(STATE_CURRENT, 0x015b0004, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b0004_Die_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0004
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b0005, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b0005_Die_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0005
;
#line 491 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
EDeath  eDeath ;
#line 492 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
eDeath  . eLastDamage  . penInflictor  = m_penDeathInflictor ;
#line 493 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_Die, FALSE, eDeath );return TRUE; ASSERT(FALSE); return TRUE;};BOOL CAirElemental::
#line 500 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CAirElemental_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CAirElemental::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 502 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(!(m_tmWindNextFire  < _pTimer  -> CurrentTick  ())){ Jump(STATE_CURRENT,0x015b0011, FALSE, EInternal());return TRUE;}
#line 503 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_FIREPROJECTILES  , AOF_NORESTART );
#line 504 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_iWind  = 0;
#line 505 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PlaySound  (m_soFire  , SOUND_FIREWINDBLAST  , SOF_3D );
#line 507 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(1.8f);
Jump(STATE_CURRENT, 0x015b0007, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b0007_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0007
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b0008, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b0008_Fire_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0008
;
#line 508 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Jump(STATE_CURRENT,0x015b000b, FALSE, EInternal());return TRUE;}BOOL CAirElemental::H0x015b000b_Fire_05(const CEntityEvent &__eeInput)
#line 509 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b000b
if(!(m_iWind  < 5)){ Jump(STATE_CURRENT,0x015b000c, FALSE, EInternal());return TRUE;}
#line 510 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT3D vFirePos ;
#line 511 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vFirePos  = Lerp  (m_fWindBlastFirePosBegin  * m_fAttSizeCurrent  , 
#line 512 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fWindBlastFirePosEnd  * m_fAttSizeCurrent  , 
#line 513 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
(FLOAT) m_iWind  * 0.25f);
#line 514 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ShootProjectile  (PRT_AIRELEMENTAL_WIND  , vFirePos  , 
#line 515 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ANGLE3D (30.0f - m_iWind  * 10.0 , 0.0f , 0.0f));
#line 516 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_iWind  ++;
#line 517 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x015b0009, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b0009_Fire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0009
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b000a, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b000a_Fire_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b000a
;Jump(STATE_CURRENT,0x015b000b, FALSE, EInternal());return TRUE;
#line 518 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}BOOL CAirElemental::H0x015b000c_Fire_06(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b000c

#line 519 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_tmWindNextFire  = _pTimer  -> CurrentTick  () + Lerp  (m_fWindFireTimeMin  , m_fWindFireTimeMax  , FRnd  ());
#line 521 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(ElementalModel  () -> GetAnimLength  (ELEMENTAL_ANIM_FIREPROJECTILES ) - 1.75f);
Jump(STATE_CURRENT, 0x015b000d, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b000d_Fire_07(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b000d
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b000e, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b000e_Fire_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b000e
;
#line 523 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_IDLE  , AOF_LOOPING  | AOF_SMOOTHCHANGE );
#line 525 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(0.05f);
Jump(STATE_CURRENT, 0x015b000f, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b000f_Fire_09(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b000f
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b0010, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b0010_Fire_10(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0010
;
#line 527 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Return(STATE_CURRENT,EReturn  ());
#line 527 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return TRUE;Jump(STATE_CURRENT,0x015b0011, FALSE, EInternal());return TRUE;}BOOL CAirElemental::H0x015b0011_Fire_11(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0011

#line 530 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_FIRETWISTER  , AOF_NORESTART );
#line 532 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PlaySound  (m_soFire  , SOUND_FIRETWISTER  , SOF_3D );
#line 533 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(4.0f);
Jump(STATE_CURRENT, 0x015b0012, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b0012_Fire_12(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0012
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b0013, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b0013_Fire_13(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0013
;
#line 535 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT3D vOffset ;
#line 537 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(((CMovableEntity  &) * m_penEnemy ) . en_vCurrentTranslationAbsolute  . Length  () == 0.0f){
#line 539 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT3D vPlayerToThis  = GetPlacement  () . pl_PositionVector  - m_penEnemy  -> GetPlacement  () . pl_PositionVector ;
#line 540 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vPlayerToThis  . Normalize  ();
#line 541 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vOffset  = FLOAT3D (vPlayerToThis  * (FRnd  () * 10.0f + 5.0f));
#line 542 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
LaunchTwister  (vOffset );
#line 544 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vOffset  = FLOAT3D (- (FRnd  () * 5.0f + 15.0f) , 0.0f , (FRnd  () - 0.5f) * 20.0f) * ((CMovableEntity  &) * m_penEnemy ) . GetRotationMatrix  ();
#line 545 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
LaunchTwister  (vOffset );
#line 547 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vOffset  = FLOAT3D (+ (FRnd  () * 5.0f + 15.0f) , 0.0f , 20.0f) * ((CMovableEntity  &) * m_penEnemy ) . GetRotationMatrix  ();
#line 548 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
LaunchTwister  (vOffset );
#line 550 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}else {
#line 551 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT3D vPlayerSpeed  = ((CMovableEntity  &) * m_penEnemy ) . en_vCurrentTranslationAbsolute ;
#line 552 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(vPlayerSpeed  . Length  () > 15.0f){
#line 553 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vPlayerSpeed  . Normalize  ();
#line 554 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vPlayerSpeed  = vPlayerSpeed  * 15.0f;
#line 555 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 556 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vOffset  = vPlayerSpeed  * (2.0f + FRnd  ());
#line 557 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT3D vToPlayer  = ((CMovableEntity  &) * m_penEnemy ) . GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector ;
#line 558 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vToPlayer  . Normalize  ();
#line 559 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vToPlayer  *= 15.0f + FRnd  () * 5.0f;
#line 560 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vOffset  -= vToPlayer ;
#line 561 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
LaunchTwister  (vOffset );
#line 563 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
LaunchTwister  (FLOAT3D (0.0f , 0.0f , 0.0f));
#line 564 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
LaunchTwister  (vOffset  + FLOAT3D (+ 5.0f + FRnd  () * 5.0f , 0.0f , - 15.0f - FRnd  () * 5.0f));
#line 565 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 569 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(ElementalModel  () -> GetAnimLength  (ELEMENTAL_ANIM_FIRETWISTER ) - 4.0f);
Jump(STATE_CURRENT, 0x015b0014, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b0014_Fire_14(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0014
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b0015, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b0015_Fire_15(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0015
;
#line 571 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_IDLE  , AOF_LOOPING  | AOF_SMOOTHCHANGE );
#line 572 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(0.05f);
Jump(STATE_CURRENT, 0x015b0016, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b0016_Fire_16(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0016
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b0017, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b0017_Fire_17(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0017
;
#line 574 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Return(STATE_CURRENT,EReturn  ());
#line 574 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CAirElemental::
#line 577 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Hit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CAirElemental_Hit
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CAirElemental::Hit expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 578 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Jump(STATE_CURRENT, STATE_CAirElemental_Fire, TRUE, EVoid());return TRUE;
#line 579 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Return(STATE_CURRENT,EReturn  ());
#line 579 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CAirElemental::
#line 585 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Death(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CAirElemental_Death
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CAirElemental::Death expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 587 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fFadeStartTime  = _pTimer  -> CurrentTick  ();
#line 588 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bFadeOut  = TRUE ;
#line 589 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fFadeTime  = 2.0f;
#line 590 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(m_fFadeTime );
Jump(STATE_CURRENT, 0x015b001a, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b001a_Death_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b001a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b001b, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b001b_Death_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b001b
;
#line 591 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
STATE_CEnemyBase_Death, FALSE;
Jump(STATE_CURRENT, 0x015b001c, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b001c_Death_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b001c
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyBase_Death, FALSE, EVoid());return TRUE;case EVENTCODE_EEnd: Jump(STATE_CURRENT,0x015b001d, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b001d_Death_04(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b001d
const EEnd&__e= (EEnd&)__eeInput;
;
#line 593 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Return(STATE_CURRENT,EEnd  ());
#line 593 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CAirElemental::
#line 600 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Grow(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CAirElemental_Grow
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CAirElemental::Grow expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 602 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ASSERT  (m_fAttSizeRequested  > m_fAttSizeCurrent );
#line 603 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fLastSize  = m_fTargetSize  = m_fAttSizeCurrent ;
#line 605 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
PlaySound  (m_soSound  , SOUND_ROAR  , SOF_3D );
#line 606 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_IDLE  , AOF_NORESTART );
#line 609 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetDesiredRotation  (ANGLE3D (0.0f , 0.0f , 0.0f));
#line 610 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bAttGrow  = TRUE ;
#line 611 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Jump(STATE_CURRENT,0x015b0021, FALSE, EInternal());return TRUE;}BOOL CAirElemental::H0x015b0021_Grow_03(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0021
if(!(m_fLastSize  < m_fAttSizeRequested )){ Jump(STATE_CURRENT,0x015b0022, FALSE, EInternal());return TRUE;}
#line 613 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(m_penEnemy ){
#line 614 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT3D vToTarget ;
#line 615 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ANGLE3D aToTarget ;
#line 616 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vToTarget  = m_penEnemy  -> GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector ;
#line 617 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
vToTarget  . Normalize  ();
#line 618 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
DirectionVectorToAngles  (vToTarget  , aToTarget );
#line 619 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
aToTarget  (1) = aToTarget  (1) - GetPlacement  () . pl_OrientationAngle  (1);
#line 620 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
aToTarget  (1) = NormalizeAngle  (aToTarget  (1));
#line 621 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetDesiredRotation  (FLOAT3D (aToTarget  (1) / 2.0f , 0.0f , 0.0f));
#line 622 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 625 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fLastSize  = m_fTargetSize ;
#line 626 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fTargetSize  += m_fGrowSpeed  * _pTimer  -> TickQuantum ;
#line 633 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
FLOAT fMiddleSize  = Lerp  (m_fAttSizeCurrent  , m_fAttSizeRequested  , 0.33f);
#line 634 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(m_fLastSize  <= fMiddleSize  && fMiddleSize  < m_fTargetSize ){
#line 635 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(m_iSize  < 2){
#line 636 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ChangeCollisionBoxIndexWhenPossible  (m_iSize  + 1);
#line 637 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}else if(TRUE ){
#line 638 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ForceCollisionBoxIndexChange  (m_iSize  + 1);
#line 639 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 640 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 642 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(_pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x015b001f, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b001f_Grow_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b001f
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b0020, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b0020_Grow_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0020
;Jump(STATE_CURRENT,0x015b0021, FALSE, EInternal());return TRUE;
#line 643 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}BOOL CAirElemental::H0x015b0022_Grow_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0022

#line 644 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bAttGrow  = FALSE ;
#line 646 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fAttSizeCurrent  = afGrowArray  [ m_iSize  ] [ 1 ];
#line 648 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fGrowSpeed  *= 2.0f;
#line 649 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
if(m_iSize  == 1){
#line 650 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
GetModelObject  () -> PlayAnim  (AIRELEMENTAL_ANIM_SIZE50  , AOF_LOOPING );
#line 651 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}
#line 653 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CAirElemental::
#line 656 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalLoop(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CAirElemental_ElementalLoop
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CAirElemental::ElementalLoop expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 657 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x015b0024, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b0024_ElementalLoop_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0024
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):
#line 659 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{const EBegin&e= (EBegin&)__eeInput;

#line 660 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Call(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE;
#line 661 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}ASSERT(FALSE);break;case(EVENTCODE_EElementalGrow):
#line 663 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
{const EElementalGrow&e= (EElementalGrow&)__eeInput;

#line 664 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Call(STATE_CURRENT, STATE_CAirElemental_Grow, TRUE, EVoid());return TRUE;
#line 665 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}ASSERT(FALSE);break;default:{
#line 667 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
return TRUE;
#line 668 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}ASSERT(FALSE);break;
#line 669 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}return TRUE;}BOOL CAirElemental::H0x015b0025_ElementalLoop_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0025
 ASSERT(FALSE); return TRUE;};BOOL CAirElemental::
#line 672 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CAirElemental_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CAirElemental::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 675 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
InitAsEditorModel  ();
#line 677 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 678 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 679 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 681 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
en_fDensity  = 10000.0f;
#line 682 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fDamageWounded  = 1e6f;
#line 684 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_sptType  = SPT_AIRSPOUTS ;
#line 685 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bBoss  = TRUE ;
#line 686 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetHealth  (15000.0f);
#line 687 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fMaxHealth  = 15000.0f;
#line 689 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fWalkSpeed  = 0.0f;
#line 690 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 245.0f);
#line 691 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fAttackRunSpeed  = m_fWalkSpeed ;
#line 692 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_aAttackRotateSpeed  = m_aWalkRotateSpeed ;
#line 693 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fCloseRunSpeed  = m_fWalkSpeed ;
#line 694 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_aCloseRotateSpeed  = m_aWalkRotateSpeed ;
#line 696 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fAttackDistance  = 500.0f;
#line 697 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fCloseDistance  = 60.0f;
#line 698 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fStopDistance  = 30.0f;
#line 699 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fAttackFireTime  = 4.0f;
#line 700 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fCloseFireTime  = 4.0f;
#line 701 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fIgnoreRange  = 1000.0f;
#line 702 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_iScore  = 500000;
#line 704 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
eiAirElemental  . vSourceCenter  [ 1 ] = AIRBOSS_EYES_HEIGHT  * m_fAttSizeBegin ;
#line 705 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
eiAirElemental  . vTargetCenter  [ 1 ] = AIRBOSS_BODY_HEIGHT  * m_fAttSizeBegin ;
#line 708 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetModel  (MODEL_INVISIBLE );
#line 709 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
AddAttachmentToModel  (this  , * GetModelObject  () , AIRELEMENTAL_ATTACHMENT_BODY  , MODEL_ELEMENTAL  , TEXTURE_ELEMENTAL  , 0 , 0 , TEXTURE_DETAIL_ELEM );
#line 710 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
CAttachmentModelObject  & amo0  = * GetModelObject  () -> GetAttachmentModel  (AIRELEMENTAL_ATTACHMENT_BODY );
#line 711 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fAttPosY  = amo0  . amo_plRelative  . pl_PositionVector  (2);
#line 712 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
StandingAnim  ();
#line 714 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_fAttSizeCurrent  = m_fAttSizeBegin ;
#line 716 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
GetModelObject  () -> StretchModel  (FLOAT3D (1.0f , 1.0f , 1.0f));
#line 717 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ModelChangeNotify  ();
#line 718 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> StretchModel  (FLOAT3D (m_fAttSizeBegin  , m_fAttSizeBegin  , m_fAttSizeBegin ));
#line 720 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bRenderParticles  = FALSE ;
#line 721 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(_pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x015b0026, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b0026_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0026
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b0027, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b0027_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0027
;
#line 723 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_emEmiter  . Initialize  (this );
#line 724 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_emEmiter  . em_etType  = ET_AIR_ELEMENTAL ;
#line 726 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_tmDeath  = 1e6f;
#line 743 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x015b0028, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b0028_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0028
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETrigger):{const ETrigger&e= (ETrigger&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x015b0029, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 747 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
}return TRUE;}BOOL CAirElemental::H0x015b0029_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b0029

#line 749 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetCollisionFlags  (ECF_AIR );
#line 750 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetPhysicsFlags  (EPF_MODEL_WALKING );
#line 752 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_RAISE  , AOF_NORESTART );
#line 753 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bRenderParticles  = TRUE ;
#line 755 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bInitialAnim  = TRUE ;
#line 757 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
SetTimerAfter(ElementalModel  () -> GetAnimLength  (ELEMENTAL_ANIM_RAISE ));
Jump(STATE_CURRENT, 0x015b002a, FALSE, EBegin());return TRUE;}BOOL CAirElemental::H0x015b002a_Main_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b002a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x015b002b, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CAirElemental::H0x015b002b_Main_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x015b002b
;
#line 759 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ChangeCollisionBoxIndexWhenPossible  (AIRELEMENTAL_COLLISION_BOX_COLLISION01 );
#line 762 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
GetModelObject  () -> PlayAnim  (AIRELEMENTAL_ANIM_DEFAULT  , AOF_LOOPING );
#line 764 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
ElementalModel  () -> PlayAnim  (ELEMENTAL_ANIM_IDLE  , AOF_LOOPING );
#line 765 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bInitialAnim  = FALSE ;
#line 766 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_bFloat  = TRUE ;
#line 768 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
m_tmWindNextFire  = _pTimer  -> CurrentTick  () + 10.0f;
#line 771 "C:/MyMod/Sources/EntitiesMP/AirElemental.es"
Jump(STATE_CURRENT, STATE_CAirElemental_ElementalLoop, TRUE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};