/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 3 "C:/MyMod/Sources/EntitiesMP/Beast.es"

#include "StdH.h"
#include "Models/Enemies/Beast/Beast.h"
#include "EntitiesMP/WorldSettingsController.h"
#include "EntitiesMP/BackgroundViewer.h"

#include <EntitiesMP/Beast.h>
#include <EntitiesMP/Beast_tables.h>
#line 19 "C:/MyMod/Sources/EntitiesMP/Beast.es"

static _tmLastStandingAnim =0.0f;  
#define BEAST_STRETCH 2.0f
#define BIG_BEAST_STRETCH 12.0f
#define HUGE_BEAST_STRETCH 30.0f

// info structure
static EntityInfo eiBeastHuge = {
  EIBT_FLESH, 10000.0f,
  0.0f, 2.0f*HUGE_BEAST_STRETCH, 0.0f,     // source (eyes)
  0.0f, 1.5f*HUGE_BEAST_STRETCH, 0.0f,     // target (body)
};
static EntityInfo eiBeastNormal = {
  EIBT_FLESH, 1500.0f,
  0.0f, 2.0f*BEAST_STRETCH, 0.0f,     // source (eyes)
  0.0f, 1.5f*BEAST_STRETCH, 0.0f,     // target (body)
};
static EntityInfo eiBeastBig = {
  EIBT_FLESH, 5000.0f,
  0.0f, 2.0f*BIG_BEAST_STRETCH, 0.0f,     // source (eyes)
  0.0f, 1.5f*BIG_BEAST_STRETCH, 0.0f,     // target (body)
};

void CBeast::SetDefaultProperties(void) {
  m_bcType = BT_NORMAL ;
  m_iCounter = 0;
  m_bBeBoss = FALSE ;
  CEnemyBase::SetDefaultProperties();
}
  CTString CBeast::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 75 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 76 "C:/MyMod/Sources/EntitiesMP/Beast.es"
CTString str ;
#line 77 "C:/MyMod/Sources/EntitiesMP/Beast.es"
str  . PrintF  (TRANS  ("A Reptiloid killed %s") , strPlayerName );
#line 78 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return str ;
#line 79 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  const CTFileName & CBeast::GetComputerMessageName(void)const {
#line 81 "C:/MyMod/Sources/EntitiesMP/Beast.es"
static DECLARE_CTFILENAME  (fnmNormal  , "Data\\Messages\\Enemies\\BeastNormal.txt");
#line 82 "C:/MyMod/Sources/EntitiesMP/Beast.es"
static DECLARE_CTFILENAME  (fnmBig  , "Data\\Messages\\Enemies\\BeastBig.txt");
#line 83 "C:/MyMod/Sources/EntitiesMP/Beast.es"
static DECLARE_CTFILENAME  (fnmHuge  , "DataMP\\Messages\\Enemies\\BeastBiggest.txt");
#line 84 "C:/MyMod/Sources/EntitiesMP/Beast.es"
switch(m_bcType ){
#line 85 "C:/MyMod/Sources/EntitiesMP/Beast.es"
default  : ASSERT  (FALSE );
#line 86 "C:/MyMod/Sources/EntitiesMP/Beast.es"
case BT_NORMAL : return fnmNormal ;
#line 87 "C:/MyMod/Sources/EntitiesMP/Beast.es"
case BT_BIG : return fnmBig ;
#line 88 "C:/MyMod/Sources/EntitiesMP/Beast.es"
case BT_HUGE : return fnmHuge ;
#line 89 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 90 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 91 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::Precache(void) {
#line 92 "C:/MyMod/Sources/EntitiesMP/Beast.es"
CEnemyBase  :: Precache  ();
#line 93 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_IDLE );
#line 94 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_SIGHT );
#line 95 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_WOUND );
#line 96 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_ANGER );
#line 97 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_FIRE );
#line 98 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_KICK );
#line 99 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheModel  (MODEL_BEAST );
#line 100 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheTexture  (TEXTURE_BEAST_NORMAL );
#line 101 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheTexture  (TEXTURE_BEAST_BIG );
#line 102 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_NORMAL ){
#line 103 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_DEATH );
#line 104 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_BEAST_PROJECTILE );
#line 105 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else {
#line 106 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_DEATHBIG );
#line 107 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_BEAST_BIG_PROJECTILE );
#line 108 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 109 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 112 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void * CBeast::GetEntityInfo(void) {
#line 113 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_NORMAL ){
#line 114 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return & eiBeastNormal ;
#line 115 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else if(m_bcType  == BT_HUGE ){
#line 116 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return & eiBeastHuge ;
#line 117 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else {
#line 118 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return & eiBeastBig ;
#line 119 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 120 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 122 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::ShakeItBaby(FLOAT tmShaketime,FLOAT fPower) 
#line 123 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 124 "C:/MyMod/Sources/EntitiesMP/Beast.es"
CWorldSettingsController  * pwsc  = GetWSC  (this );
#line 125 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(pwsc  != NULL ){
#line 126 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_tmShakeStarted  = tmShaketime ;
#line 127 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_vShakePos  = GetPlacement  () . pl_PositionVector ;
#line 128 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_fShakeFalloff  = 400.0f;
#line 129 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_fShakeFade  = 3.0f;
#line 131 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_fShakeIntensityZ  = 0.0f;
#line 132 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_tmShakeFrequencyZ  = 5.0f;
#line 133 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_fShakeIntensityY  = 0.1f * fPower ;
#line 134 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_tmShakeFrequencyY  = 5.0f;
#line 135 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_fShakeIntensityB  = 2.5f * fPower ;
#line 136 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_tmShakeFrequencyB  = 7.2f;
#line 138 "C:/MyMod/Sources/EntitiesMP/Beast.es"
pwsc  -> m_bShakeFadeIn  = FALSE ;
#line 139 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 140 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 142 "C:/MyMod/Sources/EntitiesMP/Beast.es"
FLOAT CBeast::GetCrushHealth(void) 
#line 143 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 144 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG ){
#line 145 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return 100.0f;
#line 146 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else if(m_bcType  == BT_HUGE ){
#line 147 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return 200.0f;
#line 148 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 149 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return 0.0f;
#line 150 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 152 "C:/MyMod/Sources/EntitiesMP/Beast.es"
BOOL CBeast::ForcesCannonballToExplode(void) 
#line 153 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 154 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return TRUE ;
#line 155 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 158 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 159 "C:/MyMod/Sources/EntitiesMP/Beast.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 160 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 163 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(dmtType  == DMT_BULLET  && fDamageAmmount  > 100.0f)
#line 164 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 165 "C:/MyMod/Sources/EntitiesMP/Beast.es"
fDamageAmmount  *= 0.5f;
#line 166 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 169 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG  && dmtType  == DMT_CANNONBALL )
#line 170 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 171 "C:/MyMod/Sources/EntitiesMP/Beast.es"
fDamageAmmount  *= 0.3333f;
#line 172 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 175 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(! IsOfClass  (penInflictor  , "Beast")){
#line 176 "C:/MyMod/Sources/EntitiesMP/Beast.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 177 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 178 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 182 "C:/MyMod/Sources/EntitiesMP/Beast.es"
INDEX CBeast::AnimForDamage(FLOAT fDamage) {
#line 183 "C:/MyMod/Sources/EntitiesMP/Beast.es"
INDEX iAnim ;
#line 184 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if((m_bcType  == BT_BIG  || m_bcType  == BT_HUGE ) && GetHealth  () <= m_fMaxHealth  / 2){
#line 185 "C:/MyMod/Sources/EntitiesMP/Beast.es"
iAnim  = BEAST_ANIM_ANGER ;
#line 186 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else {
#line 187 "C:/MyMod/Sources/EntitiesMP/Beast.es"
iAnim  = BEAST_ANIM_WOUND ;
#line 188 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 189 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (iAnim  , 0);
#line 190 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return iAnim ;
#line 191 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 194 "C:/MyMod/Sources/EntitiesMP/Beast.es"
INDEX CBeast::AnimForDeath(void) {
#line 195 "C:/MyMod/Sources/EntitiesMP/Beast.es"
INDEX iAnim ;
#line 196 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG  || m_bcType  == BT_HUGE ){
#line 197 "C:/MyMod/Sources/EntitiesMP/Beast.es"
iAnim  = BEAST_ANIM_DEATHBIG ;
#line 198 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else {
#line 199 "C:/MyMod/Sources/EntitiesMP/Beast.es"
iAnim  = BEAST_ANIM_DEATH ;
#line 200 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 202 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (iAnim  , 0);
#line 203 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return iAnim ;
#line 204 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 206 "C:/MyMod/Sources/EntitiesMP/Beast.es"
FLOAT CBeast::WaitForDust(FLOAT3D & vStretch) {
#line 207 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(GetModelObject  () -> GetAnim  () == BEAST_ANIM_DEATH )
#line 208 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 209 "C:/MyMod/Sources/EntitiesMP/Beast.es"
vStretch  = FLOAT3D (1 , 1 , 2) * 2.0f;
#line 210 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return 0.3f;
#line 211 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 212 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return - 1.0f;
#line 213 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 215 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::DeathNotify(void) {
#line 216 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ChangeCollisionBoxIndexWhenPossible  (BEAST_COLLISION_BOX_DEATH );
#line 217 "C:/MyMod/Sources/EntitiesMP/Beast.es"
en_fDensity  = 500.0f;
#line 218 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 221 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::StandingAnim(void) {
#line 222 "C:/MyMod/Sources/EntitiesMP/Beast.es"
_tmLastStandingAnim  = _pTimer  -> CurrentTick  ();
#line 223 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_IDLE  , AOF_LOOPING  | AOF_NORESTART );
#line 224 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 226 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::WalkingAnim(void) {
#line 227 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(_pTimer  -> CurrentTick  () >= _tmLastStandingAnim  - _pTimer  -> TickQuantum  && 
#line 228 "C:/MyMod/Sources/EntitiesMP/Beast.es"
_pTimer  -> CurrentTick  () <= _tmLastStandingAnim  + _pTimer  -> TickQuantum )
#line 229 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 230 "C:/MyMod/Sources/EntitiesMP/Beast.es"
BREAKPOINT ;
#line 231 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 233 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG  || m_bcType  == BT_HUGE ){
#line 234 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_WALKBIG  , AOF_LOOPING  | AOF_NORESTART );
#line 235 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else {
#line 236 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_WALK  , AOF_LOOPING  | AOF_NORESTART );
#line 237 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 238 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 240 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::RunningAnim(void) {
#line 241 "C:/MyMod/Sources/EntitiesMP/Beast.es"
WalkingAnim  ();
#line 242 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 243 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::RotatingAnim(void) {
#line 244 "C:/MyMod/Sources/EntitiesMP/Beast.es"
WalkingAnim  ();
#line 245 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 248 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::IdleSound(void) {
#line 249 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 250 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 251 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::SightSound(void) {
#line 252 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 253 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 254 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::WoundSound(void) {
#line 255 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if((m_bcType  == BT_BIG  || m_bcType  == BT_HUGE ) && GetHealth  () <= m_fMaxHealth  / 2){
#line 256 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_ANGER  , SOF_3D );
#line 257 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else {
#line 258 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_WOUND  , SOF_3D );
#line 259 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 260 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 261 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::DeathSound(void) {
#line 262 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_NORMAL ){
#line 263 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 264 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else {
#line 265 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_DEATHBIG  , SOF_3D );
#line 266 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 267 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
  
#line 271 "C:/MyMod/Sources/EntitiesMP/Beast.es"
void CBeast::EnemyPostInit(void) 
#line 272 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 273 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_soSound  . Set3DParameters  (160.0f , 50.0f , 2.0f , 1.0f);
#line 274 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
BOOL CBeast::
#line 280 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Death(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBeast_Death
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBeast::Death expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 281 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_NORMAL ){
#line 282 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_Death, FALSE, EVoid());return TRUE;
#line 283 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 286 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StopMoving  ();
#line 287 "C:/MyMod/Sources/EntitiesMP/Beast.es"
DeathSound  ();
#line 288 "C:/MyMod/Sources/EntitiesMP/Beast.es"
LeaveStain  (TRUE );
#line 290 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetPhysicsFlags  (EPF_MODEL_CORPSE );
#line 291 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetCollisionFlags  (ECF_CORPSE );
#line 292 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetFlags  (GetFlags  () | ENF_SEETHROUGH );
#line 294 "C:/MyMod/Sources/EntitiesMP/Beast.es"
RemoveFromFuss  ();
#line 296 "C:/MyMod/Sources/EntitiesMP/Beast.es"
DeathNotify  ();
#line 298 "C:/MyMod/Sources/EntitiesMP/Beast.es"
AnimForDeath  ();
#line 299 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.9f);
Jump(STATE_CURRENT, 0x01500001, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500001_Death_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500002_Death_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500002
;
#line 300 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG ){
#line 301 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ShakeItBaby  (_pTimer  -> CurrentTick  () , 2.0f);
#line 302 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else {
#line 303 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ShakeItBaby  (_pTimer  -> CurrentTick  () , 3.0f);
#line 304 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 305 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(2.3f - 0.9f);
Jump(STATE_CURRENT, 0x01500003, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500003_Death_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500004, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500004_Death_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500004
;
#line 306 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG ){
#line 307 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ShakeItBaby  (_pTimer  -> CurrentTick  () , 5.0f);
#line 308 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else {
#line 309 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ShakeItBaby  (_pTimer  -> CurrentTick  () , 7.0f);
#line 310 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 313 "C:/MyMod/Sources/EntitiesMP/Beast.es"
CPlacement3D plFX  = GetPlacement  ();
#line 314 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ESpawnEffect  ese ;
#line 315 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 316 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ese  . vStretch  = FLOAT3D (1 , 1 , 2) * 15.0f;
#line 317 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ese  . vNormal  = FLOAT3D (0 , 1 , 0);
#line 318 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ese  . betType  = BET_DUST_FALL ;
#line 319 "C:/MyMod/Sources/EntitiesMP/Beast.es"
CPlacement3D plSmoke  = plFX ;
#line 320 "C:/MyMod/Sources/EntitiesMP/Beast.es"
plSmoke  . pl_PositionVector  += FLOAT3D (0 , 0.35f * ese  . vStretch  (2) , 0);
#line 321 "C:/MyMod/Sources/EntitiesMP/Beast.es"
CEntityPointer penFX  = CreateEntity  (plSmoke  , CLASS_BASIC_EFFECT );
#line 322 "C:/MyMod/Sources/EntitiesMP/Beast.es"
penFX  -> Initialize  (ese );
#line 324 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (BEAST_ANIM_DEATHBIG ) - 2.3f);
Jump(STATE_CURRENT, 0x01500005, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500005_Death_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500005
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500006, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500006_Death_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500006
;
#line 325 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Return(STATE_CURRENT,EEnd  ());
#line 325 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBeast::
#line 331 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBeast_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBeast::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 334 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_WALKTOIDLE  , AOF_SMOOTHCHANGE );
#line 335 "C:/MyMod/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500008, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500008_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500008
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500009, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500009_Fire_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500009
const EReturn&__e= (EReturn&)__eeInput;
;
#line 337 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(!(m_bcType  == BT_NORMAL )){ Jump(STATE_CURRENT,0x01500010, FALSE, EInternal());return TRUE;}
#line 339 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_ATTACK  , AOF_SMOOTHCHANGE );
#line 340 "C:/MyMod/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x0150000a, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150000a_Fire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x0150000b, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150000b_Fire_04(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000b
const EReturn&__e= (EReturn&)__eeInput;
;
#line 341 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 342 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.51f);
Jump(STATE_CURRENT, 0x0150000c, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150000c_Fire_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000c
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0150000d, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150000d_Fire_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000d
;
#line 344 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ShootProjectile  (PRT_BEAST_PROJECTILE  , FLOAT3D (0.0f , 1.5f * BEAST_STRETCH  , 0.0f) , 
#line 345 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ANGLE3D (AngleDeg  ((FRnd  () - 0.5) * 30.0f) , AngleDeg  (FRnd  () * 10.0f) , 0));
#line 346 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.3f);
Jump(STATE_CURRENT, 0x0150000e, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150000e_Fire_07(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000e
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0150000f, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150000f_Fire_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000f
;Jump(STATE_CURRENT,0x01500010, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500010_Fire_09(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500010

#line 349 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(!(m_bcType  == BT_BIG )){ Jump(STATE_CURRENT,0x0150001f, FALSE, EInternal());return TRUE;}
#line 351 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(!(GetHealth  () <= m_fMaxHealth  / 2)){ Jump(STATE_CURRENT,0x01500017, FALSE, EInternal());return TRUE;}
#line 353 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iCounter  = 0;
#line 354 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT,0x01500015, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500015_Fire_14(const CEntityEvent &__eeInput)
#line 355 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500015
if(!(m_iCounter  < 6)){ Jump(STATE_CURRENT,0x01500016, FALSE, EInternal());return TRUE;}
#line 356 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_ATTACKFAST  , AOF_SMOOTHCHANGE );
#line 357 "C:/MyMod/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500011, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500011_Fire_10(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500011
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500012, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500012_Fire_11(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500012
const EReturn&__e= (EReturn&)__eeInput;
;
#line 359 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 360 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.34f);
Jump(STATE_CURRENT, 0x01500013, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500013_Fire_12(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500013
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500014, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500014_Fire_13(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500014
;
#line 361 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ShootProjectile  (PRT_BEAST_BIG_PROJECTILE  , FLOAT3D (0.0f , 1.5f * BIG_BEAST_STRETCH  , 0.0f) , 
#line 362 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ANGLE3D (0.0f , 0.0f , 0.0f));
#line 365 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iCounter  ++;Jump(STATE_CURRENT,0x01500015, FALSE, EInternal());return TRUE;
#line 366 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}BOOL CBeast::H0x01500016_Fire_15(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500016

#line 367 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fAttackFireTime  = 7.0f;Jump(STATE_CURRENT,0x01500017, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500017_Fire_16(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500017

#line 370 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(!(GetHealth  () > m_fMaxHealth  / 2)){ Jump(STATE_CURRENT,0x0150001e, FALSE, EInternal());return TRUE;}
#line 372 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iCounter  = 0;
#line 373 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT,0x0150001c, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150001c_Fire_21(const CEntityEvent &__eeInput)
#line 374 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001c
if(!(m_iCounter  < 3)){ Jump(STATE_CURRENT,0x0150001d, FALSE, EInternal());return TRUE;}
#line 375 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_ATTACK  , AOF_SMOOTHCHANGE );
#line 376 "C:/MyMod/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500018, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500018_Fire_17(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500018
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500019, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500019_Fire_18(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500019
const EReturn&__e= (EReturn&)__eeInput;
;
#line 378 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 379 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.5f);
Jump(STATE_CURRENT, 0x0150001a, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150001a_Fire_19(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0150001b, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150001b_Fire_20(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001b
;
#line 380 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ShootProjectile  (PRT_BEAST_BIG_PROJECTILE  , FLOAT3D (0.0f , 1.5f * BIG_BEAST_STRETCH  , 0.0f) , 
#line 381 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ANGLE3D (0.0f , 0.0f , 0.0f));
#line 385 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iCounter  ++;Jump(STATE_CURRENT,0x0150001c, FALSE, EInternal());return TRUE;
#line 386 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}BOOL CBeast::H0x0150001d_Fire_22(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001d
Jump(STATE_CURRENT,0x0150001e, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150001e_Fire_23(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001e
Jump(STATE_CURRENT,0x0150001f, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150001f_Fire_24(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001f

#line 390 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(!(m_bcType  == BT_HUGE )){ Jump(STATE_CURRENT,0x0150002e, FALSE, EInternal());return TRUE;}
#line 392 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(!(GetHealth  () <= m_fMaxHealth  / 2)){ Jump(STATE_CURRENT,0x01500026, FALSE, EInternal());return TRUE;}
#line 394 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iCounter  = 0;
#line 395 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT,0x01500024, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500024_Fire_29(const CEntityEvent &__eeInput)
#line 396 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500024
if(!(m_iCounter  < 6)){ Jump(STATE_CURRENT,0x01500025, FALSE, EInternal());return TRUE;}
#line 397 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_ATTACKFAST  , AOF_SMOOTHCHANGE );
#line 398 "C:/MyMod/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500020, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500020_Fire_25(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500020
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500021, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500021_Fire_26(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500021
const EReturn&__e= (EReturn&)__eeInput;
;
#line 400 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 401 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.34f);
Jump(STATE_CURRENT, 0x01500022, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500022_Fire_27(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500022
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500023, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500023_Fire_28(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500023
;
#line 402 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ShootProjectile  (PRT_BEAST_BIG_PROJECTILE  , FLOAT3D (0.0f , 1.5f * HUGE_BEAST_STRETCH  , 0.0f) , 
#line 403 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ANGLE3D (0.0f , 0.0f , 0.0f));
#line 406 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iCounter  ++;Jump(STATE_CURRENT,0x01500024, FALSE, EInternal());return TRUE;
#line 407 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}BOOL CBeast::H0x01500025_Fire_30(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500025

#line 408 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fAttackFireTime  = 7.0f;Jump(STATE_CURRENT,0x01500026, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500026_Fire_31(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500026

#line 411 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(!(GetHealth  () > m_fMaxHealth  / 2)){ Jump(STATE_CURRENT,0x0150002d, FALSE, EInternal());return TRUE;}
#line 413 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iCounter  = 0;
#line 414 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT,0x0150002b, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150002b_Fire_36(const CEntityEvent &__eeInput)
#line 415 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002b
if(!(m_iCounter  < 3)){ Jump(STATE_CURRENT,0x0150002c, FALSE, EInternal());return TRUE;}
#line 416 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_ATTACK  , AOF_SMOOTHCHANGE );
#line 417 "C:/MyMod/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500027, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500027_Fire_32(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500027
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500028, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500028_Fire_33(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500028
const EReturn&__e= (EReturn&)__eeInput;
;
#line 419 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 420 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.5f);
Jump(STATE_CURRENT, 0x01500029, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500029_Fire_34(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500029
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0150002a, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150002a_Fire_35(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002a
;
#line 421 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ShootProjectile  (PRT_BEAST_BIG_PROJECTILE  , FLOAT3D (0.0f , 1.5f * HUGE_BEAST_STRETCH  , 0.0f) , 
#line 422 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ANGLE3D (0.0f , 0.0f , 0.0f));
#line 426 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iCounter  ++;Jump(STATE_CURRENT,0x0150002b, FALSE, EInternal());return TRUE;
#line 427 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}BOOL CBeast::H0x0150002c_Fire_37(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002c
Jump(STATE_CURRENT,0x0150002d, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150002d_Fire_38(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002d
Jump(STATE_CURRENT,0x0150002e, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150002e_Fire_39(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002e

#line 431 "C:/MyMod/Sources/EntitiesMP/Beast.es"
MaybeSwitchToAnotherPlayer  ();
#line 433 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(FRnd  () / 2 + _pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x0150002f, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150002f_Fire_40(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002f
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500030, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500030_Fire_41(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500030
;
#line 435 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(!(m_penEnemy  != NULL )){ Jump(STATE_CURRENT,0x01500036, FALSE, EInternal());return TRUE;}
#line 437 "C:/MyMod/Sources/EntitiesMP/Beast.es"
FLOAT fEnemyDistance  = CalcDist  (m_penEnemy );
#line 438 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(!(fEnemyDistance  > m_fCloseDistance  * 1.25f)){ Jump(STATE_CURRENT,0x01500035, FALSE, EInternal());return TRUE;}
#line 440 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_IDLETOWALK  , AOF_SMOOTHCHANGE );
#line 441 "C:/MyMod/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500031, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500031_Fire_42(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500031
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500032, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500032_Fire_43(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500032
const EReturn&__e= (EReturn&)__eeInput;
;
#line 442 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (BEAST_ANIM_IDLETOWALK ) / 2.0f - _pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x01500033, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500033_Fire_44(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500033
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500034, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500034_Fire_45(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500034
;Jump(STATE_CURRENT,0x01500035, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500035_Fire_46(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500035
Jump(STATE_CURRENT,0x01500036, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500036_Fire_47(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500036

#line 447 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Return(STATE_CURRENT,EReturn  ());
#line 447 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBeast::
#line 451 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Hit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBeast_Hit
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBeast::Hit expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 453 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_KICK  , 0);
#line 454 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.45f);
Jump(STATE_CURRENT, 0x01500038, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500038_Hit_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500038
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500039, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500039_Hit_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500039
;
#line 459 "C:/MyMod/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_KICK  , SOF_3D );
#line 460 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(CalcDist  (m_penEnemy ) < m_fCloseDistance ){
#line 461 "C:/MyMod/Sources/EntitiesMP/Beast.es"
FLOAT3D vDirection  = m_penEnemy  -> GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector ;
#line 462 "C:/MyMod/Sources/EntitiesMP/Beast.es"
vDirection  . Normalize  ();
#line 463 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG ){
#line 464 "C:/MyMod/Sources/EntitiesMP/Beast.es"
InflictDirectDamage  (m_penEnemy  , this  , DMT_CLOSERANGE  , 80.0f , FLOAT3D (0 , 0 , 0) , vDirection );
#line 465 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else if(m_bcType  == BT_HUGE ){
#line 466 "C:/MyMod/Sources/EntitiesMP/Beast.es"
InflictDirectDamage  (m_penEnemy  , this  , DMT_CLOSERANGE  , 120.0f , FLOAT3D (0 , 0 , 0) , vDirection );
#line 467 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}else {
#line 468 "C:/MyMod/Sources/EntitiesMP/Beast.es"
InflictDirectDamage  (m_penEnemy  , this  , DMT_CLOSERANGE  , 40.0f , FLOAT3D (0 , 0 , 0) , vDirection );
#line 469 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 470 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 476 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.45f);
Jump(STATE_CURRENT, 0x0150003a, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150003a_Hit_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150003a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0150003b, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150003b_Hit_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150003b
;
#line 477 "C:/MyMod/Sources/EntitiesMP/Beast.es"
MaybeSwitchToAnotherPlayer  ();
#line 478 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Return(STATE_CURRENT,EReturn  ());
#line 478 "C:/MyMod/Sources/EntitiesMP/Beast.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBeast::
#line 484 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBeast_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBeast::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 486 "C:/MyMod/Sources/EntitiesMP/Beast.es"
InitAsModel  ();
#line 487 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetPhysicsFlags  (EPF_MODEL_WALKING );
#line 488 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetCollisionFlags  (ECF_MODEL );
#line 489 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 491 "C:/MyMod/Sources/EntitiesMP/Beast.es"
en_fDensity  = 1100.0f;
#line 493 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetModel  (MODEL_BEAST );
#line 494 "C:/MyMod/Sources/EntitiesMP/Beast.es"
StandingAnim  ();
#line 496 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fWalkSpeed  = FRnd  () * 2 + 5.0f;
#line 497 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 20.0f + 50.0f);
#line 498 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fCloseRunSpeed  = FRnd  () + 10.0f;
#line 499 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 100 + 900.0f);
#line 501 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fAttackDistance  = 500.0f;
#line 502 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fCloseDistance  = 0.0f;
#line 503 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fStopDistance  = 0.0f;
#line 504 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fCloseFireTime  = 1.0f;
#line 505 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fIgnoreRange  = 750.0f;
#line 506 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_bBoss  = m_bBeBoss ;
#line 507 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fStopDistance  = 5.0f;
#line 508 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fCloseDistance  = 7.0f;
#line 509 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_tmGiveUp  = Max  (m_tmGiveUp  , 10.0f);
#line 512 "C:/MyMod/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_NORMAL )
#line 513 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 514 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fAttackRunSpeed  = 6.0f;
#line 515 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_aAttackRotateSpeed  = AngleDeg  (3600.0f);
#line 516 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetHealth  (400.0f);
#line 517 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetModelMainTexture  (TEXTURE_BEAST_NORMAL );
#line 518 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fBlowUpAmount  = 10000.0f;
#line 519 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fBodyParts  = 4;
#line 520 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fDamageWounded  = 250.0f;
#line 521 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iScore  = 5000;
#line 523 "C:/MyMod/Sources/EntitiesMP/Beast.es"
GetModelObject  () -> StretchModel  (FLOAT3D (BEAST_STRETCH  , BEAST_STRETCH  , BEAST_STRETCH ));
#line 524 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ModelChangeNotify  ();
#line 525 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_sptType  = SPT_SLIME ;
#line 526 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fAttackFireTime  = 3.0f;
#line 527 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 528 "C:/MyMod/Sources/EntitiesMP/Beast.es"
else if(m_bcType  == BT_BIG )
#line 529 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 530 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fAttackRunSpeed  = 25.0f;
#line 531 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_aAttackRotateSpeed  = AngleDeg  (600.0f);
#line 532 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetHealth  (3000.0f);
#line 533 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetModelMainTexture  (TEXTURE_BEAST_BIG );
#line 534 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fBlowUpAmount  = 10000.0f;
#line 535 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fBodyParts  = 6;
#line 536 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fDamageWounded  = 650.0f;
#line 537 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iScore  = 25000;
#line 538 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fStopDistance  = 15;
#line 539 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fCloseDistance  = 20;
#line 541 "C:/MyMod/Sources/EntitiesMP/Beast.es"
GetModelObject  () -> StretchModel  (FLOAT3D (BIG_BEAST_STRETCH  , BIG_BEAST_STRETCH  , BIG_BEAST_STRETCH ));
#line 542 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ModelChangeNotify  ();
#line 543 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_sptType  = SPT_BLOOD ;
#line 544 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fAttackFireTime  = 5.0f;
#line 545 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 546 "C:/MyMod/Sources/EntitiesMP/Beast.es"
else 
#line 547 "C:/MyMod/Sources/EntitiesMP/Beast.es"
{
#line 548 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fAttackRunSpeed  = 35.0f;
#line 549 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_aAttackRotateSpeed  = AngleDeg  (600.0f);
#line 550 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetHealth  (6000.0f);
#line 551 "C:/MyMod/Sources/EntitiesMP/Beast.es"
SetModelMainTexture  (TEXTURE_BEAST_HUGE );
#line 552 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fBlowUpAmount  = 100000.0f;
#line 553 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fBodyParts  = 6;
#line 554 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fDamageWounded  = 1650.0f;
#line 555 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_iScore  = 40000;
#line 556 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fStopDistance  = 75;
#line 557 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fCloseDistance  = 80;
#line 558 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fAttackDistance  = 1000.0f;
#line 559 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fIgnoreRange  = 1200.0f;
#line 561 "C:/MyMod/Sources/EntitiesMP/Beast.es"
GetModelObject  () -> StretchModel  (FLOAT3D (HUGE_BEAST_STRETCH  , HUGE_BEAST_STRETCH  , HUGE_BEAST_STRETCH ));
#line 562 "C:/MyMod/Sources/EntitiesMP/Beast.es"
ModelChangeNotify  ();
#line 563 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_sptType  = SPT_BLOOD ;
#line 564 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fAttackFireTime  = 5.0f;
#line 565 "C:/MyMod/Sources/EntitiesMP/Beast.es"
}
#line 567 "C:/MyMod/Sources/EntitiesMP/Beast.es"
m_fMaxHealth  = GetHealth  ();
#line 570 "C:/MyMod/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};