/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/MyMod/Sources/EntitiesMP/Boneman.es"

#include "StdH.h"
#include "Models/Enemies/Boneman/Boneman.h"

#include <EntitiesMP/Boneman.h>
#include <EntitiesMP/Boneman_tables.h>
#line 9 "C:/MyMod/Sources/EntitiesMP/Boneman.es"

// info structure
static EntityInfo eiBoneman = {
 EIBT_BONES, 250.0f,
 0.0f, 1.9f, 0.0f,    // source (eyes)
 0.0f, 1.9f, 0.0f,    // target (body)
};

#define BONES_HIT 2.8f
#define FIRE_RIGHT_HAND     FLOAT3D( 0.25f, 1.5f, 0.0f)
#define FIRE_LEFT_HAND      FLOAT3D(-0.25f, 1.5f, 0.0f)

void CBoneman::SetDefaultProperties(void) {
  m_bFistHit = FALSE ;
  m_bTouchAnother = FALSE ;
  m_soFeet.SetOwner(this);
m_soFeet.Stop_internal();
  m_bRunSoundPlaying = FALSE ;
  CEnemyBase::SetDefaultProperties();
}
  
#line 55 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::Precache(void) {
#line 56 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
CEnemyBase  :: Precache  ();
#line 57 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheSound  (SOUND_IDLE );
#line 58 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheSound  (SOUND_SIGHT );
#line 59 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheSound  (SOUND_WOUND );
#line 60 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheSound  (SOUND_FIRE );
#line 61 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheSound  (SOUND_KICK );
#line 62 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheSound  (SOUND_PUNCH );
#line 63 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheSound  (SOUND_DEATH );
#line 64 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheSound  (SOUND_RUN );
#line 66 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheModel  (MODEL_BONEMAN_BODY );
#line 67 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheModel  (MODEL_BONEMAN_HAND );
#line 68 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheModel  (MODEL_BONEMAN_LEGS );
#line 70 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_BONEMAN_FIRE );
#line 71 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  CTString CBoneman::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 75 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
{
#line 76 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
CTString str ;
#line 77 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(eDeath  . eLastDamage  . dmtType  == DMT_CLOSERANGE ){
#line 78 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
str  . PrintF  (TRANS  ("%s was ripped apart by a Kleer") , strPlayerName );
#line 79 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}else {
#line 80 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
str  . PrintF  (TRANS  ("%s was killed by a Kleer") , strPlayerName );
#line 81 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 82 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return str ;
#line 83 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  const CTFileName & CBoneman::GetComputerMessageName(void)const {
#line 86 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
static DECLARE_CTFILENAME  (fnm  , "Data\\Messages\\Enemies\\Boneman.txt");
#line 87 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return fnm ;
#line 88 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 91 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void * CBoneman::GetEntityInfo(void) {
#line 92 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return & eiBoneman ;
#line 93 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 96 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 97 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 98 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
{
#line 100 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(! IsOfClass  (penInflictor  , "Boneman")){
#line 101 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 102 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 103 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 105 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::LeaveStain(BOOL bGrow) 
#line 106 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
{
#line 108 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 111 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
INDEX CBoneman::AnimForDamage(FLOAT fDamage) {
#line 112 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
INDEX iAnim ;
#line 113 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
switch(IRnd  () % 5){
#line 114 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
case 0: iAnim  = BONEMAN_ANIM_WOUNDCRITICAL01 ;break ;
#line 115 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
case 1: iAnim  = BONEMAN_ANIM_WOUNDCRITICAL02 ;break ;
#line 116 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
case 2: iAnim  = BONEMAN_ANIM_WOUNDCRITICAL03 ;break ;
#line 117 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
case 3: iAnim  = BONEMAN_ANIM_FALL01 ;break ;
#line 118 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
case 4: iAnim  = BONEMAN_ANIM_FALL02 ;break ;
#line 119 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
default  : ASSERTALWAYS  ("Boneman unknown damage");
#line 120 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 121 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
StartModelAnim  (iAnim  , 0);
#line 122 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
DeactivateRunningSound  ();
#line 123 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return iAnim ;
#line 124 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 127 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
INDEX CBoneman::AnimForDeath(void) {
#line 128 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
INDEX iAnim ;
#line 129 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
switch(IRnd  () % 2){
#line 130 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
case 0: iAnim  = BONEMAN_ANIM_DEATHTOBACK ;break ;
#line 131 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
case 1: iAnim  = BONEMAN_ANIM_DEATHTOFRONT ;break ;
#line 132 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
default  : ASSERTALWAYS  ("Boneman unknown death");
#line 133 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 134 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
StartModelAnim  (iAnim  , 0);
#line 135 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
DeactivateRunningSound  ();
#line 136 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return iAnim ;
#line 137 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 139 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT CBoneman::WaitForDust(FLOAT3D & vStretch) {
#line 140 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(GetModelObject  () -> GetAnim  () == BONEMAN_ANIM_DEATHTOBACK )
#line 141 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
{
#line 142 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vStretch  = FLOAT3D (1 , 1 , 2) * 1.0f;
#line 143 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return 0.48f;
#line 144 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 145 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
else if(GetModelObject  () -> GetAnim  () == BONEMAN_ANIM_DEATHTOFRONT )
#line 146 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
{
#line 147 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vStretch  = FLOAT3D (1 , 1 , 2) * 0.75f;
#line 148 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return 0.48f;
#line 149 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 150 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return - 1.0f;
#line 151 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 153 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::DeathNotify(void) {
#line 154 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
ChangeCollisionBoxIndexWhenPossible  (BONEMAN_COLLISION_BOX_DEATH );
#line 155 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 158 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::StandingAnim(void) {
#line 159 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
StartModelAnim  (BONEMAN_ANIM_STANDLOOP  , AOF_LOOPING  | AOF_NORESTART );
#line 160 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
DeactivateRunningSound  ();
#line 161 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 162 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::WalkingAnim(void) {
#line 163 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
StartModelAnim  (BONEMAN_ANIM_WALKLOOP  , AOF_LOOPING  | AOF_NORESTART );
#line 164 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
DeactivateRunningSound  ();
#line 165 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 166 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::RunningAnim(void) {
#line 167 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
StartModelAnim  (BONEMAN_ANIM_RUNLOOP  , AOF_LOOPING  | AOF_NORESTART );
#line 168 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
ActivateRunningSound  ();
#line 169 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 170 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::RotatingAnim(void) {
#line 171 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
StartModelAnim  (BONEMAN_ANIM_WALKLOOP  , AOF_LOOPING  | AOF_NORESTART );
#line 172 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
DeactivateRunningSound  ();
#line 173 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 176 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::IdleSound(void) {
#line 177 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 178 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 179 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::SightSound(void) {
#line 180 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 181 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 182 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::WoundSound(void) {
#line 183 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PlaySound  (m_soSound  , SOUND_WOUND  , SOF_3D );
#line 184 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 185 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::DeathSound(void) {
#line 186 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 187 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 191 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::ActivateRunningSound(void) 
#line 192 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
{
#line 193 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(! m_bRunSoundPlaying ){
#line 194 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PlaySound  (m_soFeet  , SOUND_RUN  , SOF_3D  | SOF_LOOP );
#line 195 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_bRunSoundPlaying  = TRUE ;
#line 196 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 197 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 198 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::DeactivateRunningSound(void) 
#line 199 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
{
#line 200 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_soFeet  . Stop  ();
#line 201 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_bRunSoundPlaying  = FALSE ;
#line 202 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
  
#line 208 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
void CBoneman::BlowUp(void) {
#line 210 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOATaabbox3D box ;
#line 211 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
GetBoundingBox  (box );
#line 212 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT fEntitySize  = box  . Size  () . MaxNorm  ();
#line 214 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D vNormalizedDamage  = m_vDamage  - m_vDamage  * (m_fBlowUpAmount  / m_vDamage  . Length  ());
#line 215 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vNormalizedDamage  /= Sqrt  (vNormalizedDamage  . Length  ());
#line 217 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vNormalizedDamage  *= 0.75f;
#line 219 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D vBodySpeed  = en_vCurrentTranslationAbsolute  - en_vGravityDir  * (en_vGravityDir  % en_vCurrentTranslationAbsolute );
#line 222 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Debris_Begin  (EIBT_BONES  , DPT_NONE  , BET_NONE  , fEntitySize  , vNormalizedDamage  , vBodySpeed  , 5.0f , 2.0f);
#line 224 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Debris_Spawn  (this  , this  , MODEL_BONEMAN_BODY  , TEXTURE_BONEMAN  , 0 , 0 , 0 , 0 , 0.0f , 
#line 225 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D (FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f));
#line 226 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Debris_Spawn  (this  , this  , MODEL_BONEMAN_HAND  , TEXTURE_BONEMAN  , 0 , 0 , 0 , 0 , 0.0f , 
#line 227 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D (FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f));
#line 228 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Debris_Spawn  (this  , this  , MODEL_BONEMAN_HAND  , TEXTURE_BONEMAN  , 0 , 0 , 0 , 0 , 0.0f , 
#line 229 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D (FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f));
#line 230 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Debris_Spawn  (this  , this  , MODEL_BONEMAN_LEGS  , TEXTURE_BONEMAN  , 0 , 0 , 0 , 0 , 0.0f , 
#line 231 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D (FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f , FRnd  () * 0.6f + 0.2f));
#line 234 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SwitchToEditorModel  ();
#line 235 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 236 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 237 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
BOOL CBoneman::
#line 247 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBoneman_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBoneman::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 249 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
StartModelAnim  (BONEMAN_ANIM_ATTACKCLOSELOOP  , 0);
#line 250 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
DeactivateRunningSound  ();
#line 251 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetTimerAfter(0.35f);
Jump(STATE_CURRENT, 0x01310001, FALSE, EBegin());return TRUE;}BOOL CBoneman::H0x01310001_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01310002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBoneman::H0x01310002_Fire_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310002
;
#line 252 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
ShootProjectile  (PRT_BONEMAN_FIRE  , FIRE_RIGHT_HAND  , ANGLE3D (0 , 0 , 0));
#line 253 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 254 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetTimerAfter(0.45f);
Jump(STATE_CURRENT, 0x01310003, FALSE, EBegin());return TRUE;}BOOL CBoneman::H0x01310003_Fire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01310004, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBoneman::H0x01310004_Fire_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310004
;
#line 255 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
ShootProjectile  (PRT_BONEMAN_FIRE  , FIRE_LEFT_HAND  , ANGLE3D (0 , 0 , 0));
#line 256 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 257 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetTimerAfter(FRnd  () / 3 + 0.6f);
Jump(STATE_CURRENT, 0x01310005, FALSE, EBegin());return TRUE;}BOOL CBoneman::H0x01310005_Fire_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310005
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01310006, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBoneman::H0x01310006_Fire_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310006
;
#line 259 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Return(STATE_CURRENT,EReturn  ());
#line 259 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBoneman::
#line 262 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Hit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBoneman_Hit
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBoneman::Hit expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 264 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(CalcDist  (m_penEnemy ) < BONES_HIT ){
#line 265 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Jump(STATE_CURRENT, STATE_CBoneman_HitWithBones, TRUE, EVoid());return TRUE;
#line 268 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}else if(CalcDist  (m_penEnemy ) < 10.0f){
#line 269 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Jump(STATE_CURRENT, STATE_CBoneman_JumpOnEnemy, TRUE, EVoid());return TRUE;
#line 270 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 273 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fShootTime  = _pTimer  -> CurrentTick  () + 0.5f;
#line 274 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Return(STATE_CURRENT,EReturn  ());
#line 274 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBoneman::
#line 278 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
JumpOnEnemy(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBoneman_JumpOnEnemy
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBoneman::JumpOnEnemy expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 279 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
StartModelAnim  (BONEMAN_ANIM_ATTACKFAR  , 0);
#line 280 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
DeactivateRunningSound  ();
#line 283 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D vDir  = (m_penEnemy  -> GetPlacement  () . pl_PositionVector  - 
#line 284 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
GetPlacement  () . pl_PositionVector ) . Normalize  ();
#line 285 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vDir  *= ! GetRotationMatrix  ();
#line 286 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vDir  *= m_fCloseRunSpeed  * 1.5f;
#line 287 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vDir  (2) = 2.5f;
#line 288 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetDesiredTranslation  (vDir );
#line 289 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PlaySound  (m_soSound  , SOUND_KICK  , SOF_3D );
#line 292 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SpawnReminder  (this  , 0.5f , 0);
#line 293 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_iChargeHitAnimation  = BONEMAN_ANIM_ATTACKFAR ;
#line 294 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fChargeHitDamage  = 20.0f;
#line 295 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fChargeHitAngle  = 0.0f;
#line 296 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fChargeHitSpeed  = 15.0f;
#line 297 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
STATE_CEnemyBase_ChargeHitEnemy, FALSE;
Jump(STATE_CURRENT, 0x01310009, FALSE, EBegin());return TRUE;}BOOL CBoneman::H0x01310009_JumpOnEnemy_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310009
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyBase_ChargeHitEnemy, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x0131000a, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBoneman::H0x0131000a_JumpOnEnemy_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x0131000a
const EReturn&__e= (EReturn&)__eeInput;
;
#line 298 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetTimerAfter(0.3f);
Jump(STATE_CURRENT, 0x0131000b, FALSE, EBegin());return TRUE;}BOOL CBoneman::H0x0131000b_JumpOnEnemy_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0131000b
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0131000c, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBoneman::H0x0131000c_JumpOnEnemy_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0131000c
;
#line 299 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Return(STATE_CURRENT,EReturn  ());
#line 299 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBoneman::
#line 303 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
HitWithBones(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBoneman_HitWithBones
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBoneman::HitWithBones expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 305 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
StartModelAnim  (BONEMAN_ANIM_ATTACKCLOSELOOP  , 0);
#line 306 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
DeactivateRunningSound  ();
#line 309 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_bFistHit  = FALSE ;
#line 310 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetTimerAfter(0.35f);
Jump(STATE_CURRENT, 0x0131000e, FALSE, EBegin());return TRUE;}BOOL CBoneman::H0x0131000e_HitWithBones_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0131000e
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0131000f, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBoneman::H0x0131000f_HitWithBones_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0131000f
;
#line 311 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(CalcDist  (m_penEnemy ) < BONES_HIT ){m_bFistHit  = TRUE ;}
#line 312 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PlaySound  (m_soSound  , SOUND_PUNCH  , SOF_3D );
#line 313 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetTimerAfter(0.10f);
Jump(STATE_CURRENT, 0x01310010, FALSE, EBegin());return TRUE;}BOOL CBoneman::H0x01310010_HitWithBones_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310010
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01310011, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBoneman::H0x01310011_HitWithBones_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310011
;
#line 314 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(CalcDist  (m_penEnemy ) < BONES_HIT ){m_bFistHit  = TRUE ;}
#line 315 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(m_bFistHit ){
#line 316 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D vDirection  = m_penEnemy  -> GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector ;
#line 317 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vDirection  . Normalize  ();
#line 319 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
InflictDirectDamage  (m_penEnemy  , this  , DMT_CLOSERANGE  , 10.0f , FLOAT3D (0 , 0 , 0) , vDirection );
#line 321 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D vSpeed ;
#line 322 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
GetHeadingDirection  (AngleDeg  (90.0f) , vSpeed );
#line 323 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vSpeed  = vSpeed  * 5.0f;
#line 324 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
KickEntity  (m_penEnemy  , vSpeed );
#line 325 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 328 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_bFistHit  = FALSE ;
#line 329 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetTimerAfter(0.25f);
Jump(STATE_CURRENT, 0x01310012, FALSE, EBegin());return TRUE;}BOOL CBoneman::H0x01310012_HitWithBones_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310012
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01310013, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBoneman::H0x01310013_HitWithBones_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310013
;
#line 330 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(CalcDist  (m_penEnemy ) < BONES_HIT ){m_bFistHit  = TRUE ;}
#line 331 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
PlaySound  (m_soSound  , SOUND_PUNCH  , SOF_3D );
#line 332 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetTimerAfter(0.10f);
Jump(STATE_CURRENT, 0x01310014, FALSE, EBegin());return TRUE;}BOOL CBoneman::H0x01310014_HitWithBones_07(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310014
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01310015, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBoneman::H0x01310015_HitWithBones_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01310015
;
#line 333 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(CalcDist  (m_penEnemy ) < BONES_HIT ){m_bFistHit  = TRUE ;}
#line 334 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(m_bFistHit ){
#line 336 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D vDirection  = m_penEnemy  -> GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector ;
#line 337 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vDirection  . Normalize  ();
#line 338 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
InflictDirectDamage  (m_penEnemy  , this  , DMT_CLOSERANGE  , 10.0f , FLOAT3D (0 , 0 , 0) , vDirection );
#line 340 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
FLOAT3D vSpeed ;
#line 341 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
GetHeadingDirection  (AngleDeg  (- 90.0f) , vSpeed );
#line 342 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
vSpeed  = vSpeed  * 5.0f;
#line 343 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
KickEntity  (m_penEnemy  , vSpeed );
#line 344 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 345 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Return(STATE_CURRENT,EReturn  ());
#line 345 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBoneman::
#line 353 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBoneman_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBoneman::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 355 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
InitAsModel  ();
#line 356 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetPhysicsFlags  (EPF_MODEL_WALKING );
#line 357 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetCollisionFlags  (ECF_MODEL );
#line 358 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 359 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetHealth  (125.0f);
#line 360 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fMaxHealth  = 125.0f;
#line 361 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
en_fDensity  = 2000.0f;
#line 364 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetModel  (MODEL_BONEMAN );
#line 365 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
SetModelMainTexture  (TEXTURE_BONEMAN );
#line 366 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
StandingAnim  ();
#line 367 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_sptType  = SPT_BONES ;
#line 369 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fWalkSpeed  = FRnd  () + 2.5f;
#line 370 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_aWalkRotateSpeed  = FRnd  () * 25.0f + 45.0f;
#line 371 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fAttackRunSpeed  = FRnd  () * 3.0f + 10.0f;
#line 372 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_aAttackRotateSpeed  = FRnd  () * 200 + 600.0f;
#line 373 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fCloseRunSpeed  = FRnd  () + 13.0f;
#line 374 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_aCloseRotateSpeed  = FRnd  () * 100 + 1000.0f;
#line 376 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fAttackDistance  = 100.0f;
#line 377 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fCloseDistance  = 30.0f;
#line 378 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fStopDistance  = 2.0f;
#line 379 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fAttackFireTime  = 3.0f;
#line 380 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fCloseFireTime  = 2.0f;
#line 381 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fIgnoreRange  = 200.0f;
#line 383 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fBlowUpAmount  = 70.0f;
#line 384 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fBodyParts  = 4;
#line 385 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fDamageWounded  = 80.0f;
#line 386 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_iScore  = 1000;
#line 387 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
if(m_fStepHeight  == - 1){
#line 388 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_fStepHeight  = 4.0f;
#line 389 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
}
#line 392 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
CEnemyBase  :: SizeModel  ();
#line 393 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_soFeet  . Set3DParameters  (80.0f , 5.0f , 1.0f , 1.0f);
#line 394 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
m_bRunSoundPlaying  = FALSE ;
#line 397 "C:/MyMod/Sources/EntitiesMP/Boneman.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};