/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_ChainsawFreak_INCLUDED
#define _EntitiesMP_ChainsawFreak_INCLUDED 1
#include <EntitiesMP/EnemyBase.h>
#include <EntitiesMP/EnemyRunInto.h>
extern "C" DECL_DLL CDLLEntityClass CChainsawFreak_DLLClass;
class CChainsawFreak : public CEnemyRunInto {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  BOOL m_bRunAttack;
  BOOL m_bSawHit;
  CEntityPointer m_penLastTouched;
  CSoundObject m_soFeet;
  BOOL m_bRunSoundPlaying;
  INDEX m_iRunType;
  BOOL m_bAttacking;
  FLOAT m_fSightSoundBegin;
  
#line 59 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
   
#line 66 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void Precache(void);
   
#line 78 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void * GetEntityInfo(void);
   
#line 82 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
FLOAT GetCrushHealth(void);
  
#line 87 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
virtual const CTFileName & GetComputerMessageName(void)const;
   
#line 99 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 100 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 108 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void AdjustDifficulty(void);
   
#line 114 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
INDEX AnimForDeath(void);
   
#line 128 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
FLOAT WaitForDust(FLOAT3D & vStretch);
   
#line 142 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void DeathNotify();
   
#line 148 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void StandingAnim(void);
   
#line 152 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void WalkingAnim(void);
   
#line 156 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void RunningAnim(void);
   
#line 173 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void ChargeAnim(void);
   
#line 176 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void RotatingAnim(void);
   
#line 182 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void IdleSound(void);
   
#line 188 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void WoundSound(void);
   
#line 191 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void DeathSound(void);
   
#line 196 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void ActivateRunningSound(void);
   
#line 203 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void DeactivateRunningSound(void);
   
#line 214 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void LiveEntityTouched(ETouch etouch);
   
#line 254 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
BOOL HigherMass(void);
   
#line 259 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void EnemyPostInit(void);
   
#line 267 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
void PreMoving();
#define  STATE_CChainsawFreak_Hit 0x01560000
  BOOL 
#line 280 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
Hit(const CEntityEvent &__eeInput);
  BOOL H0x01560001_Hit_01(const CEntityEvent &__eeInput);
  BOOL H0x01560002_Hit_02(const CEntityEvent &__eeInput);
  BOOL H0x01560003_Hit_03(const CEntityEvent &__eeInput);
  BOOL H0x01560004_Hit_04(const CEntityEvent &__eeInput);
  BOOL H0x01560005_Hit_05(const CEntityEvent &__eeInput);
  BOOL H0x01560006_Hit_06(const CEntityEvent &__eeInput);
  BOOL H0x01560007_Hit_07(const CEntityEvent &__eeInput);
  BOOL H0x01560008_Hit_08(const CEntityEvent &__eeInput);
  BOOL H0x01560009_Hit_09(const CEntityEvent &__eeInput);
#define  STATE_CChainsawFreak_AttackEnemy 0x0156000a
  BOOL 
#line 322 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
AttackEnemy(const CEntityEvent &__eeInput);
#define  STATE_CChainsawFreak_BeIdle 0x0156000b
  BOOL 
#line 329 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
BeIdle(const CEntityEvent &__eeInput);
#define  STATE_CChainsawFreak_PostRunAwayFromEnemy 0x0156000c
  BOOL 
#line 336 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
PostRunAwayFromEnemy(const CEntityEvent &__eeInput);
  BOOL H0x0156000d_PostRunAwayFromEnemy_01(const CEntityEvent &__eeInput);
  BOOL H0x0156000e_PostRunAwayFromEnemy_02(const CEntityEvent &__eeInput);
  BOOL H0x0156000f_PostRunAwayFromEnemy_03(const CEntityEvent &__eeInput);
  BOOL H0x01560010_PostRunAwayFromEnemy_04(const CEntityEvent &__eeInput);
#define  STATE_CChainsawFreak_Main 1
  BOOL 
#line 348 "C:/MyMod/Sources/EntitiesMP/ChainsawFreak.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_ChainsawFreak_INCLUDED
