/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"

#include "StdH.h"

#include <EntitiesMP/EnvironmentParticlesHolder.h>
#include <EntitiesMP/EnvironmentParticlesHolder_tables.h>
void CEnvironmentParticlesHolder::SetDefaultProperties(void) {
  m_strName = "Env. particles holder";
  m_strDescription = "";
  m_fnHeightMap = CTString("");
  m_boxHeightMap = FLOATaabbox3D(FLOAT3D (0 , 0 , 0) , FLOAT3D (1 , 1 , 1));
  m_eptType = EPTH_NONE ;
  m_penNextHolder = NULL;
  m_tmRainStart = -1.0f;
  m_tmRainEnd = -1.0f;
  m_tmSnowStart = -1.0f;
  m_tmSnowEnd = -1.0f;
  m_moHeightMapHolder.SetData(NULL);
m_moHeightMapHolder.mo_toTexture.SetData(NULL);
  m_moParticleTextureHolder.SetData(NULL);
m_moParticleTextureHolder.mo_toTexture.SetData(NULL);
  m_fnTexture = CTString("");
  m_fGrowthRenderingStep = 1.0f;
  m_fGrowthRenderingRadius = 50;
  m_fGrowthRenderingRadiusFade = 50;
  m_bGrowthHighresMap = TRUE ;
  m_iGrowthMapX = 1;
  m_iGrowthMapY = 1;
  m_fGrowthMinSize = 1.0f;
  m_fGrowthMaxSize = 1.0f;
  m_fParticlesSinkFactor = 0.0;
  m_fRainAppearLen = 10.0f;
  m_fSnowAppearLen = 10.0f;
  CRationalEntity::SetDefaultProperties();
}
  
#line 68 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
void CEnvironmentParticlesHolder::Precache(void) 
#line 69 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 70 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
CTextureData  * ptdHeightMap  = (CTextureData  *) m_moHeightMapHolder  . mo_toTexture  . GetData  ();
#line 71 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(ptdHeightMap  != NULL ){
#line 72 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
ptdHeightMap  -> Force  (TEX_CONSTANT  | TEX_STATIC  | TEX_KEEPCOLOR );
#line 73 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 74 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
  
#line 77 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
BOOL CEnvironmentParticlesHolder::IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget) 
#line 78 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 79 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(slPropertyOffset  == offsetof  (CEnvironmentParticlesHolder  , m_penNextHolder ))
#line 80 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 81 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(IsOfClass  (penTarget  , "EnvironmentParticlesHolder")){return TRUE ;}
#line 82 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
else {return FALSE ;}
#line 83 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 84 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return CEntity  :: IsTargetValid  (slPropertyOffset  , penTarget );
#line 85 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
  
#line 88 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
FLOAT CEnvironmentParticlesHolder::GetRainFactor(void) 
#line 89 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 90 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
FLOAT fRainFactor  = 0.0f;
#line 91 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
TIME  tmNow  = _pTimer  -> GetLerpedCurrentTick  ();
#line 93 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(tmNow  > m_tmRainStart  && tmNow  < m_tmRainEnd  + m_fRainAppearLen )
#line 94 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 96 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(tmNow  > m_tmRainStart  + m_fRainAppearLen  && tmNow  < m_tmRainEnd )
#line 97 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 98 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fRainFactor  = 1.0f;
#line 99 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 101 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
else if(tmNow  > m_tmRainEnd )
#line 102 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 103 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fRainFactor  = 1.0f - (tmNow  - m_tmRainEnd ) / m_fRainAppearLen ;
#line 104 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 106 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
else 
#line 107 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 108 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fRainFactor  = (tmNow  - m_tmRainStart ) / m_fRainAppearLen ;
#line 109 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 110 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 111 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return fRainFactor ;
#line 112 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
  
#line 115 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
FLOAT CEnvironmentParticlesHolder::GetSnowFactor(void) 
#line 116 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 117 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
FLOAT fSnowFactor  = 0.0f;
#line 118 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
TIME  tmNow  = _pTimer  -> GetLerpedCurrentTick  ();
#line 120 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(tmNow  > m_tmSnowStart  && tmNow  < m_tmSnowEnd  + m_fSnowAppearLen )
#line 121 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 123 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(tmNow  > m_tmSnowStart  + m_fSnowAppearLen  && tmNow  < m_tmSnowEnd )
#line 124 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 125 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fSnowFactor  = 1.0f;
#line 126 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 128 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
else if(tmNow  > m_tmSnowEnd )
#line 129 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 130 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fSnowFactor  = 1.0f - (tmNow  - m_tmSnowEnd ) / m_fSnowAppearLen ;
#line 131 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 133 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
else 
#line 134 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 135 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
fSnowFactor  = (tmNow  - m_tmSnowStart ) / m_fSnowAppearLen ;
#line 136 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 137 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 138 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return fSnowFactor ;
#line 139 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
  
#line 142 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
void CEnvironmentParticlesHolder::GetHeightMapData(CTextureData * & ptdHeightMap,FLOATaabbox3D & boxHeightMap) 
#line 143 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 144 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
ptdHeightMap  = (CTextureData  *) m_moHeightMapHolder  . mo_toTexture  . GetData  ();
#line 145 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(ptdHeightMap  != NULL ){
#line 146 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
ptdHeightMap  -> Force  (TEX_CONSTANT  | TEX_STATIC  | TEX_KEEPCOLOR );
#line 147 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 148 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
boxHeightMap  = m_boxHeightMap ;
#line 149 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
boxHeightMap  += GetPlacement  () . pl_PositionVector ;
#line 150 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
  
#line 152 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
void CEnvironmentParticlesHolder::GetParticleTexture() 
#line 153 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 155 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
BOOL CEnvironmentParticlesHolder::
#line 158 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnvironmentParticlesHolder_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnvironmentParticlesHolder::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 161 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
InitAsEditorModel  ();
#line 162 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 163 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 166 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(m_fnHeightMap  != CTString (""))
#line 167 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 168 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
try 
#line 169 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 170 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_moHeightMapHolder  . mo_toTexture  . SetData_t  (m_fnHeightMap );
#line 171 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}catch  (char  * strError ){
#line 172 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
WarningMessage  (strError );
#line 173 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 174 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 176 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(m_fnTexture  != CTString (""))
#line 177 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 178 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
try 
#line 179 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{
#line 180 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_moParticleTextureHolder  . mo_toTexture  . SetData_t  (m_fnTexture );
#line 181 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}catch  (char  * strError ){
#line 182 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
WarningMessage  (strError );
#line 183 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 184 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 188 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
if(m_fGrowthRenderingRadius  < m_fGrowthRenderingRadiusFade ){
#line 189 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_fGrowthRenderingRadiusFade  = m_fGrowthRenderingRadius ;
#line 190 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 191 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_fParticlesSinkFactor  = Clamp  (m_fParticlesSinkFactor  , 0.0f , 1.0f);
#line 194 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
SetModel  (MODEL_ENVIRONMENT_PARTICLES_HOLDER );
#line 195 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
SetModelMainTexture  (TEXTURE_ENVIRONMENT_PARTICLES_HOLDER );
#line 197 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmRainStart  = 1e5 - 1.0f;
#line 198 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmRainEnd  = 1e5;
#line 199 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmSnowStart  = 1e5 - 1.0f;
#line 200 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmSnowEnd  = 1e5;
#line 202 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
switch(m_eptType ){
#line 203 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
case EPTH_GROWTH : 
#line 204 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_strDescription  = "Growth";
#line 205 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
break ;
#line 206 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
case EPTH_RAIN : 
#line 207 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_strDescription  = "Rain";
#line 208 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
break ;
#line 209 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
case EPTH_NONE : 
#line 210 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_strDescription  = "None";
#line 211 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
break ;
#line 212 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}
#line 214 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00ed0000, FALSE, EBegin());return TRUE;}BOOL CEnvironmentParticlesHolder::H0x00ed0000_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00ed0000
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):
#line 217 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{const EBegin&e= (EBegin&)__eeInput;

#line 218 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return TRUE;
#line 219 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):
#line 221 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{const EStart&e= (EStart&)__eeInput;

#line 222 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
TIME  tmNow  = _pTimer  -> CurrentTick  ();
#line 223 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmRainStart  = tmNow ;
#line 224 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmRainEnd  = 1e6;
#line 225 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmSnowStart  = tmNow ;
#line 226 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmSnowEnd  = 1e6;
#line 227 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return TRUE;
#line 228 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):
#line 230 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
{const EStop&e= (EStop&)__eeInput;

#line 231 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
TIME  tmNow  = _pTimer  -> CurrentTick  ();
#line 232 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmRainEnd  = tmNow ;
#line 233 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
m_tmSnowEnd  = tmNow ;
#line 234 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return TRUE;
#line 235 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 236 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
}return TRUE;}BOOL CEnvironmentParticlesHolder::H0x00ed0001_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00ed0001

#line 238 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
Return(STATE_CURRENT,EVoid());
#line 238 "C:/MyMod/Sources/EntitiesMP/EnvironmentParticlesHolder.es"
return TRUE; ASSERT(FALSE); return TRUE;};