/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"

#include "StdH.h"
//#include "ModelsMP/Enemies/Grunt/Grunt.h"

#include <EntitiesMP/GruntSka.h>
#include <EntitiesMP/GruntSka_tables.h>
#line 15 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"

#define STRETCH_SOLDIER   1.2f
#define STRETCH_COMMANDER 1.4f
  
// info structure
static EntityInfo eiGruntSoldier = {
  EIBT_FLESH, 200.0f,
  0.0f, 1.9f*STRETCH_SOLDIER, 0.0f,     // source (eyes)
  0.0f, 1.3f*STRETCH_SOLDIER, 0.0f,     // target (body)
};

static EntityInfo eiGruntCommander = {
  EIBT_FLESH, 250.0f,
  0.0f, 1.9f*STRETCH_COMMANDER, 0.0f,     // source (eyes)
  0.0f, 1.3f*STRETCH_COMMANDER, 0.0f,     // target (body)
};

#define FIREPOS_SOLDIER       FLOAT3D(0.07f, 1.36f, -0.78f)*STRETCH_SOLDIER
#define FIREPOS_COMMANDER_UP  FLOAT3D(0.09f, 1.45f, -0.62f)*STRETCH_COMMANDER
#define FIREPOS_COMMANDER_DN  FLOAT3D(0.10f, 1.30f, -0.60f)*STRETCH_COMMANDER

#define COMANDER_SMC_MODEL "ModelsSKA\\Enemies\\Grunt\\Commander.smc"
#define SOLIDER_SMC_MODEL "ModelsSKA\\Enemies\\Grunt\\Grunt.smc"

#define GRUNT_MESH      
#define GRUNT_SKELETON  
#define GRUNT_ANIMSET   
#define GRUNT_TEXTURE   

#define CLEAR_ANIM_TIME   0.2f

static INDEX idGrunt_Wound          = -1;
static INDEX idGrunt_Run            = -1;
static INDEX idGrunt_IdlePatrol     = -1;
static INDEX idGrunt_IdleAttack     = -1;
static INDEX idGrunt_Fire           = -1;
static INDEX idGrunt_Default        = -1;
static INDEX idGrunt_DeathForward   = -1;
static INDEX idGrunt_DeathBackward  = -1;
static INDEX idGrunt_GunModel       = -1;

static INDEX idGrund_NormalBox      = -1;
static INDEX idGrund_DeathBox       = -1;

static CTextureObject _toStar01;

#define SHP_BASE_TEXTURE 0


void CGruntSka::SetDefaultProperties(void) {
  m_gtType = GT_SOLDIER ;
  m_soFire1.SetOwner(this);
m_soFire1.Stop_internal();
  m_soFire2.SetOwner(this);
m_soFire2.Stop_internal();
  m_fMidBoneRot = 0.0f;
  m_miTest.Clear();

  CEnemyBase::SetDefaultProperties();
}
   CGruntSka::CGruntSka(void) 
#line 95 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
{
#line 97 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrunt_Wound  = ska_GetIDFromStringTable  ("Grunt_Wound");
#line 98 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrunt_Run  = ska_GetIDFromStringTable  ("Grunt_Run");
#line 99 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrunt_IdlePatrol  = ska_GetIDFromStringTable  ("Grunt_IdlePatrol");
#line 100 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrunt_IdleAttack  = ska_GetIDFromStringTable  ("Grunt_IdleAttack");
#line 101 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrunt_Fire  = ska_GetIDFromStringTable  ("Grunt_Fire");
#line 102 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrunt_Default  = ska_GetIDFromStringTable  ("Grunt_Default");
#line 103 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrunt_DeathForward  = ska_GetIDFromStringTable  ("Grunt_DeathForward");
#line 104 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrunt_DeathBackward  = ska_GetIDFromStringTable  ("Grunt_DeathBackward");
#line 105 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrunt_GunModel  = ska_GetIDFromStringTable  ("Flamer");
#line 108 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrund_NormalBox  = ska_GetIDFromStringTable  ("Normal");
#line 109 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idGrund_DeathBox  = ska_GetIDFromStringTable  ("Death");
#line 110 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 112 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::CreateTestModelInstance() 
#line 113 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
{
#line 114 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
try {
#line 115 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_miTest  . AddMesh_t  ((CTString) "ModelsSKA\\Test\\Arm\\Arm.bm");
#line 116 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_miTest  . AddSkeleton_t  ((CTString) "ModelsSKA\\Test\\Arm\\Arm.bs");
#line 117 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_miTest  . AddAnimSet_t  ((CTString) "ModelsSKA\\Test\\Arm\\Arm.ba");
#line 118 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_miTest  . AddTexture_t  ((CTString) "ModelsSKA\\Test\\Arm\\Objects\\Arm.tex" , "Arm" , NULL );
#line 119 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_miTest  . AddColisionBox  ("Default" , FLOAT3D (- 0.5f , 0.0f , - 0.5f) , FLOAT3D (0.5f , 2.0f , 0.5f));
#line 120 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}catch  (char  * strErr ){
#line 121 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
FatalError  (strErr );
#line 122 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
#line 123 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 125 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::BuildGruntModel() 
#line 126 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
{
#line 129 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
en_pmiModelInstance  = CreateModelInstance  ("GruntSka");
#line 130 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
CModelInstance * pmi  = GetModelInstance  ();
#line 131 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
try {
#line 133 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddMesh_t  ((CTString) "ModelsSKA\\Enemies\\Grunt\\Grunt.bm");
#line 134 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddSkeleton_t  ((CTString) "ModelsSKA\\Enemies\\Grunt\\Grunt.bs");
#line 135 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddAnimSet_t  ((CTString) "ModelsSKA\\Enemies\\Grunt\\Grunt.ba");
#line 136 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddTexture_t  ((CTString) "ModelsSKA\\Enemies\\Grunt\\Soldier.tex" , "Grunt" , NULL );
#line 137 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddColisionBox  ("Default" , FLOAT3D (- 0.5f , 0.0f , - 0.5f) , FLOAT3D (0.5f , 2.0f , 0.5f));
#line 140 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
CModelInstance * pmiFlamer  = CreateModelInstance  ("Flamer");
#line 141 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> AddMesh_t  ((CTString) "ModelsSKA\\Weapons\\Flamer\\Flamer.bm");
#line 142 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> AddSkeleton_t  ((CTString) "ModelsSKA\\Weapons\\Flamer\\Flamer.bs");
#line 143 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> AddAnimSet_t  ((CTString) "ModelsSKA\\Weapons\\Flamer\\Flamer.ba");
#line 144 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> AddTexture_t  ((CTString) "ModelsSKA\\Weapons\\Flamer\\Flamer.tex" , "Flamer" , NULL );
#line 145 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> AddTexture_t  ((CTString) "ModelsSKA\\Enemies\\Grunt\\Lava04FX.tex" , "Lava04FX" , NULL );
#line 147 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> SetOffsetRot  (ANGLE3D (0 , 0 , 180));
#line 149 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddChild  (pmiFlamer );
#line 152 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
INDEX iParenBoneID  = ska_GetIDFromStringTable  ("R_Hand");
#line 153 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> SetParentBone  (iParenBoneID );
#line 156 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetSkaColisionInfo  ();
#line 157 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}catch  (char  * strErr ){
#line 158 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
FatalError  (strErr );
#line 159 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
#line 160 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 162 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::BuildCommanderModel(CEntity * penGrunt) 
#line 163 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
{
#line 164 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetSkaModel  ("ModelsSKA\\Enemies\\Grunt\\CommanderNoGun.smc");
#line 165 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
CModelInstance * pmiFlamer  = NULL ;
#line 166 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
try {
#line 167 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  = ParseSmcFile_t  ("ModelsSKA\\Weapons\\Flamer\\Flamer.smc");
#line 168 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}catch  (char  * strErr ){
#line 169 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
FatalError  (strErr );
#line 170 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
#line 172 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
INDEX iParenBoneID  = ska_GetIDFromStringTable  ("R_Hand");
#line 173 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
CModelInstance * pmi  = GetModelInstance  ();
#line 174 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmi  -> AddChild  (pmiFlamer );
#line 175 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> SetParentBone  (iParenBoneID );
#line 177 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
pmiFlamer  -> SetOffsetRot  (ANGLE3D (0 , 0 , 180));
#line 179 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetSkaColisionInfo  ();
#line 180 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  CTString CGruntSka::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 255 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
{
#line 256 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
CTString str ;
#line 257 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
str  . PrintF  (TRANS  ("A Grunt sent %s into the halls of Valhalla") , strPlayerName );
#line 258 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return str ;
#line 259 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 262 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void * CGruntSka::GetEntityInfo(void) {
#line 263 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
if(m_gtType  == GT_SOLDIER ){
#line 264 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return & eiGruntSoldier ;
#line 265 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}else if(m_gtType  == GT_COMMANDER ){
#line 266 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return & eiGruntSoldier ;
#line 267 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}else {
#line 268 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ASSERT  ("Unknown grunt type!");
#line 269 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return NULL ;
#line 270 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
#line 271 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  const CTFileName & CGruntSka::GetComputerMessageName(void)const {
#line 274 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
static DECLARE_CTFILENAME  (fnmSoldier  , "DataMP\\Messages\\Enemies\\GruntSoldier.txt");
#line 275 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
static DECLARE_CTFILENAME  (fnmCommander  , "DataMP\\Messages\\Enemies\\GruntCommander.txt");
#line 276 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
switch(m_gtType ){
#line 277 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
default  : ASSERT  (FALSE );
#line 278 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
case GT_SOLDIER : return fnmSoldier ;
#line 279 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
case GT_COMMANDER : return fnmCommander ;
#line 280 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
#line 281 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 283 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::Precache(void) {
#line 284 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
CEnemyBase  :: Precache  ();
#line 286 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
if(m_gtType  == GT_SOLDIER ){
#line 287 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_GRUNT_PROJECTILE_SOL );
#line 288 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
#line 289 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
if(m_gtType  == GT_COMMANDER ){
#line 290 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_GRUNT_PROJECTILE_COM );
#line 291 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
#line 293 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PrecacheSound  (SOUND_IDLE );
#line 294 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PrecacheSound  (SOUND_SIGHT );
#line 295 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PrecacheSound  (SOUND_WOUND );
#line 296 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PrecacheSound  (SOUND_FIRE );
#line 297 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PrecacheSound  (SOUND_DEATH );
#line 298 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 301 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 302 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 303 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
{
#line 304 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 305 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 308 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
INDEX CGruntSka::AnimForDamage(FLOAT fDamage) {
#line 309 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Wound  , AN_CLEAR  , 1 , 0);
#line 310 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return idGrunt_Wound ;
#line 311 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 314 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
INDEX CGruntSka::AnimForDeath(void) {
#line 315 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
INDEX idAnimDeath ;
#line 316 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
FLOAT3D vFront ;
#line 317 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetHeadingDirection  (0 , vFront );
#line 318 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
FLOAT fDamageDir  = m_vDamage  % vFront ;
#line 319 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
if(fDamageDir  < 0){
#line 320 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idAnimDeath  = idGrunt_DeathBackward ;
#line 321 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}else {
#line 322 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
idAnimDeath  = idGrunt_DeathForward ;
#line 323 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
#line 325 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idAnimDeath  , AN_CLEAR  , 1 , 0);
#line 327 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return idAnimDeath ;
#line 328 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 330 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
FLOAT CGruntSka::WaitForDust(FLOAT3D & vStretch) {
#line 332 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
vStretch  = FLOAT3D (1 , 1 , 2);
#line 333 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
if(GetModelInstance  () -> IsAnimationPlaying  (idGrunt_DeathBackward )){
#line 334 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return 0.5f;
#line 335 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}else if(GetModelInstance  () -> IsAnimationPlaying  (idGrunt_DeathForward )){
#line 336 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return 1.0f;
#line 337 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
#line 338 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return - 1.0f;
#line 339 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 341 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::DeathNotify(void) {
#line 342 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
INDEX iBoxIndex  = GetModelInstance  () -> GetColisionBoxIndex  (idGrund_DeathBox );
#line 343 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ASSERT  (iBoxIndex  >= 0);
#line 344 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ChangeCollisionBoxIndexWhenPossible  (iBoxIndex );
#line 345 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
en_fDensity  = 500.0f;
#line 346 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 349 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::StandingAnim(void) {
#line 350 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_IdleAttack  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 351 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 356 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::RunningAnim(void) {
#line 357 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Run  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 358 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 359 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::WalkingAnim(void) {
#line 360 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
RunningAnim  ();
#line 361 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 362 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::RotatingAnim(void) {
#line 363 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
RunningAnim  ();
#line 364 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 367 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::IdleSound(void) {
#line 368 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 369 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 370 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::SightSound(void) {
#line 371 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 372 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 373 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::WoundSound(void) {
#line 374 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soSound  , SOUND_WOUND  , SOF_3D );
#line 375 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 376 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::DeathSound(void) {
#line 377 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 378 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
  
#line 381 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
void CGruntSka::EnemyPostInit(void) 
#line 382 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
{
#line 384 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_soFire1  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 385 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_soFire2  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 386 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
BOOL CGruntSka::
#line 392 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGruntSka_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGruntSka::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 394 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
if(!(m_gtType  == GT_SOLDIER )){ Jump(STATE_CURRENT,0x01570008, FALSE, EInternal());return TRUE;}
#line 395 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
STATE_CGruntSka_SoldierAttack, TRUE;
Jump(STATE_CURRENT, 0x01570001, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570001_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CGruntSka_SoldierAttack, TRUE, EVoid());return TRUE;case EVENTCODE_EEnd: Jump(STATE_CURRENT,0x01570002, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570002_Fire_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570002
const EEnd&__e= (EEnd&)__eeInput;
;Jump(STATE_CURRENT,0x01570007, FALSE, EInternal());return TRUE;}BOOL CGruntSka::H0x01570008_Fire_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570008
if(!(m_gtType  == GT_COMMANDER )){ Jump(STATE_CURRENT,0x01570006, FALSE, EInternal());return TRUE;}
#line 398 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
STATE_CGruntSka_CommanderAttack, TRUE;
Jump(STATE_CURRENT, 0x01570003, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570003_Fire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CGruntSka_CommanderAttack, TRUE, EVoid());return TRUE;case EVENTCODE_EEnd: Jump(STATE_CURRENT,0x01570004, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570004_Fire_04(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570004
const EEnd&__e= (EEnd&)__eeInput;
;Jump(STATE_CURRENT,0x01570005, FALSE, EInternal());return TRUE;}BOOL CGruntSka::H0x01570006_Fire_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570006
{
#line 401 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ASSERT  (FALSE );
#line 402 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}Jump(STATE_CURRENT,0x01570005, FALSE, EInternal());return TRUE;}
BOOL CGruntSka::H0x01570005_Fire_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570005
Jump(STATE_CURRENT,0x01570007, FALSE, EInternal());return TRUE;}
BOOL CGruntSka::H0x01570007_Fire_07(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570007

#line 403 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
Return(STATE_CURRENT,EReturn  ());
#line 403 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CGruntSka::
#line 407 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SoldierAttack(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGruntSka_SoldierAttack
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGruntSka::SoldierAttack expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 409 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
StandingAnimFight  ();
#line 410 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.2f + FRnd  () * 0.25f);
Jump(STATE_CURRENT, 0x0157000a, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x0157000a_SoldierAttack_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0157000b, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x0157000b_SoldierAttack_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000b
;
#line 412 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1.0f , 0);
#line 414 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_SOL  , FIREPOS_SOLDIER  , ANGLE3D (0 , 0 , 0));
#line 415 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire1  , SOUND_FIRE  , SOF_3D );
#line 417 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.15f + FRnd  () * 0.1f);
Jump(STATE_CURRENT, 0x0157000c, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x0157000c_SoldierAttack_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000c
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0157000d, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x0157000d_SoldierAttack_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000d
;
#line 418 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1.0f , 0);
#line 419 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_SOL  , FIREPOS_SOLDIER  , ANGLE3D (0 , 0 , 0));
#line 420 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire2  , SOUND_FIRE  , SOF_3D );
#line 423 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(FRnd  () * 0.333f);
Jump(STATE_CURRENT, 0x0157000e, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x0157000e_SoldierAttack_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000e
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0157000f, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x0157000f_SoldierAttack_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000f
;
#line 424 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
Return(STATE_CURRENT,EEnd  ());
#line 424 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CGruntSka::
#line 428 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
CommanderAttack(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGruntSka_CommanderAttack
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGruntSka::CommanderAttack expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 429 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
StandingAnimFight  ();
#line 430 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.2f + FRnd  () * 0.25f);
Jump(STATE_CURRENT, 0x01570011, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570011_CommanderAttack_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570011
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570012, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570012_CommanderAttack_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570012
;
#line 440 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1 , 0);
#line 441 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_COM  , FIREPOS_COMMANDER_DN  , ANGLE3D (- 20 , 0 , 0));
#line 442 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire1  , SOUND_FIRE  , SOF_3D );
#line 444 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.035f);
Jump(STATE_CURRENT, 0x01570013, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570013_CommanderAttack_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570013
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570014, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570014_CommanderAttack_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570014
;
#line 445 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1 , 0);
#line 446 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_COM  , FIREPOS_COMMANDER_DN  , ANGLE3D (- 10 , 0 , 0));
#line 447 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire2  , SOUND_FIRE  , SOF_3D );
#line 449 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.035f);
Jump(STATE_CURRENT, 0x01570015, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570015_CommanderAttack_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570015
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570016, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570016_CommanderAttack_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570016
;
#line 450 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1 , 0);
#line 451 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_COM  , FIREPOS_COMMANDER_DN  , ANGLE3D (0 , 0 , 0));
#line 452 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire1  , SOUND_FIRE  , SOF_3D );
#line 454 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.035f);
Jump(STATE_CURRENT, 0x01570017, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570017_CommanderAttack_07(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570017
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570018, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x01570018_CommanderAttack_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570018
;
#line 455 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1 , 0);
#line 456 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_COM  , FIREPOS_COMMANDER_DN  , ANGLE3D (10 , 0 , 0));
#line 457 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire2  , SOUND_FIRE  , SOF_3D );
#line 459 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(0.035f);
Jump(STATE_CURRENT, 0x01570019, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x01570019_CommanderAttack_09(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570019
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0157001a, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x0157001a_CommanderAttack_10(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001a
;
#line 460 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> AddAnimation  (idGrunt_Fire  , AN_CLEAR  , 1 , 0);
#line 461 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ShootProjectile  (PRT_GRUNT_PROJECTILE_COM  , FIREPOS_COMMANDER_DN  , ANGLE3D (20 , 0 , 0));
#line 462 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
PlaySound  (m_soFire2  , SOUND_FIRE  , SOF_3D );
#line 464 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetTimerAfter(FRnd  () * 0.5f);
Jump(STATE_CURRENT, 0x0157001b, FALSE, EBegin());return TRUE;}BOOL CGruntSka::H0x0157001b_CommanderAttack_11(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001b
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0157001c, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGruntSka::H0x0157001c_CommanderAttack_12(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001c
;
#line 465 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
Return(STATE_CURRENT,EEnd  ());
#line 465 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CGruntSka::
#line 471 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGruntSka_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGruntSka::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 473 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
InitAsSkaModel  ();
#line 474 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 475 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetCollisionFlags  (ECF_MODEL );
#line 476 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 477 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
en_tmMaxHoldBreath  = 5.0f;
#line 478 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
en_fDensity  = 2000.0f;
#line 485 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
switch(m_gtType ){
#line 486 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
case GT_SOLDIER : 
#line 487 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetSkaModel  (SOLIDER_SMC_MODEL );
#line 491 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fWalkSpeed  = FRnd  () + 2.5f;
#line 492 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 500.0f);
#line 493 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fAttackRunSpeed  = FRnd  () + 6.5f;
#line 494 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 495 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fCloseRunSpeed  = FRnd  () + 6.5f;
#line 496 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 498 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fAttackDistance  = 80.0f;
#line 499 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fCloseDistance  = 0.0f;
#line 500 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fStopDistance  = 8.0f;
#line 501 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fAttackFireTime  = 2.0f;
#line 502 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fCloseFireTime  = 1.0f;
#line 503 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fIgnoreRange  = 200.0f;
#line 505 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fBlowUpAmount  = 80.0f;
#line 506 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fBodyParts  = 4;
#line 507 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fDamageWounded  = 0.0f;
#line 508 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_iScore  = 500;
#line 509 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetHealth  (40.0f);
#line 510 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fMaxHealth  = 40.0f;
#line 512 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> StretchModel  (FLOAT3D (STRETCH_SOLDIER  , STRETCH_SOLDIER  , STRETCH_SOLDIER ));
#line 513 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
break ;
#line 515 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
case GT_COMMANDER : 
#line 517 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetSkaModel  (COMANDER_SMC_MODEL );
#line 520 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fWalkSpeed  = FRnd  () + 2.5f;
#line 521 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 500.0f);
#line 522 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fAttackRunSpeed  = FRnd  () + 8.0f;
#line 523 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 524 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fCloseRunSpeed  = FRnd  () + 8.0f;
#line 525 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 527 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fAttackDistance  = 90.0f;
#line 528 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fCloseDistance  = 0.0f;
#line 529 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fStopDistance  = 15.0f;
#line 530 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fAttackFireTime  = 4.0f;
#line 531 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fCloseFireTime  = 2.0f;
#line 533 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fIgnoreRange  = 200.0f;
#line 535 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fBodyParts  = 5;
#line 536 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fDamageWounded  = 0.0f;
#line 537 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_iScore  = 800;
#line 538 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
SetHealth  (60.0f);
#line 539 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
m_fMaxHealth  = 60.0f;
#line 541 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
GetModelInstance  () -> StretchModel  (FLOAT3D (STRETCH_COMMANDER  , STRETCH_COMMANDER  , STRETCH_COMMANDER ));
#line 542 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
break ;
#line 543 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
}
#line 545 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
ModelChangeNotify  ();
#line 546 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
StandingAnim  ();
#line 549 "C:/MyMod/Sources/EntitiesMP/GruntSka.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};