/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"

#include "StdH.h"
#include "Models/Items/ItemHolder/ItemHolder.h"

#include <EntitiesMP/MessageItem.h>
#include <EntitiesMP/MessageItem_tables.h>
CEntityEvent *EMessageItem::MakeCopy(void) { CEntityEvent *peeCopy = new EMessageItem(*this); return peeCopy;}
EMessageItem::EMessageItem() : CEntityEvent(EVENTCODE_EMessageItem) {;
 ClearToDefault(fnmMessage);
};
#line 14 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"


void CMessageItem::SetDefaultProperties(void) {
  m_strName = "MessageItem";
  m_strDescription = "";
  m_fnmMessage = CTString("");
  m_iSoundComponent = 0;
  CItem::SetDefaultProperties();
}
  
#line 41 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
void CMessageItem::Precache(void) {
#line 42 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
PrecacheSound  (SOUND_KEY );
#line 43 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
}
  
#line 45 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
BOOL CMessageItem::FillEntityStatistics(EntityStats * pes) 
#line 46 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
{
#line 47 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
pes  -> es_strName  = "Pergament";
#line 48 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
pes  -> es_ctCount  = 1;
#line 49 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
pes  -> es_ctAmmount  = 1;
#line 50 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
pes  -> es_fValue  = 1;
#line 51 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
pes  -> es_iScore  = 0;
#line 52 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
return TRUE ;
#line 53 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
}
  
#line 55 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
void CMessageItem::RenderParticles(void) {
#line 57 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
if(GetRenderType  () != CEntity  :: RT_MODEL ){
#line 58 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
return ;
#line 59 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
}
#line 60 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
Particles_Stardust  (this  , 0.9f , 0.70f , PT_STAR08  , 32);
#line 61 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
}
  
#line 65 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
void CMessageItem::SetProperties(void) 
#line 66 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
{
#line 67 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
m_fRespawnTime  = (m_fCustomRespawnTime  > 0) ? m_fCustomRespawnTime  : 10.0f;
#line 68 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
m_strDescription  = m_fnmMessage  . FileName  ();
#line 71 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
AddItem  (MODEL_PERGAMENT  , TEXTURE_PERGAMENT  , 0 , 0 , 0);
#line 73 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
AddFlare  (MODEL_FLARE  , TEXTURE_FLARE  , FLOAT3D (0 , 0.2f , 0) , FLOAT3D (1 , 1 , 0.3f));
#line 74 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
StretchItem  (FLOAT3D (1.0f , 1.0f , 1.0f));
#line 75 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
m_iSoundComponent  = SOUND_KEY ;
#line 76 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
}
BOOL CMessageItem::
#line 79 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
ItemCollected(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CMessageItem_ItemCollected
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EPass, "CMessageItem::ItemCollected expects 'EPass' as input!");  const EPass &epass = (const EPass &)__eeInput;
#line 80 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
ASSERT  (epass  . penOther  != NULL );
#line 83 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
EMessageItem  eMessage ;
#line 84 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
eMessage  . fnmMessage  = m_fnmMessage ;
#line 86 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
if(epass  . penOther  -> ReceiveItem  (eMessage )){
#line 88 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
m_soPick  . Set3DParameters  (50.0f , 1.0f , 1.0f , 1.0f);
#line 89 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
PlaySound  (m_soPick  , m_iSoundComponent  , SOF_3D );
#line 90 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
m_fPickSoundLen  = GetSoundLength  (m_iSoundComponent );
#line 91 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
Jump(STATE_CURRENT, STATE_CItem_ItemReceived, FALSE, EVoid());return TRUE;
#line 92 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
}
#line 93 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
Return(STATE_CURRENT,EVoid());
#line 93 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CMessageItem::
#line 96 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CMessageItem_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CMessageItem::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 97 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
Initialize  ();
#line 98 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
StartModelAnim  (ITEMHOLDER_ANIM_SMALLOSCILATION  , AOF_LOOPING  | AOF_NORESTART );
#line 99 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
ForceCollisionBoxIndexChange  (ITEMHOLDER_COLLISION_BOX_SMALL );
#line 100 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
SetProperties  ();
#line 102 "C:/MyMod/Sources/EntitiesMP/MessageItem.es"
Jump(STATE_CURRENT, STATE_CItem_ItemLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};