/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_Projectile_INCLUDED
#define _EntitiesMP_Projectile_INCLUDED 1
#include <EntitiesMP/BasicEffects.h>
#include <EntitiesMP/Light.h>
#include <EntitiesMP/Flame.h>
extern DECL_DLL CEntityPropertyEnumType ProjectileType_enum;
enum ProjectileType {
  PRT_ROCKET = 0,
  PRT_GRENADE = 1,
  PRT_FLAME = 2,
  PRT_LASER_RAY = 3,
  PRT_WALKER_ROCKET = 4,
  PRT_CATMAN_FIRE = 10,
  PRT_HEADMAN_FIRECRACKER = 11,
  PRT_HEADMAN_ROCKETMAN = 12,
  PRT_HEADMAN_BOMBERMAN = 13,
  PRT_BONEMAN_FIRE = 14,
  PRT_WOMAN_FIRE = 15,
  PRT_DRAGONMAN_FIRE = 16,
  PRT_DRAGONMAN_STRONG_FIRE = 17,
  PRT_STONEMAN_FIRE = 18,
  PRT_STONEMAN_BIG_FIRE = 19,
  PRT_STONEMAN_LARGE_FIRE = 20,
  PRT_LAVAMAN_BIG_BOMB = 21,
  PRT_LAVAMAN_BOMB = 22,
  PRT_LAVAMAN_STONE = 23,
  PRT_ICEMAN_FIRE = 27,
  PRT_ICEMAN_BIG_FIRE = 28,
  PRT_ICEMAN_LARGE_FIRE = 29,
  PRT_HUANMAN_FIRE = 41,
  PRT_FISHMAN_FIRE = 42,
  PRT_MANTAMAN_FIRE = 43,
  PRT_CYBORG_LASER = 44,
  PRT_CYBORG_BOMB = 45,
  PRT_LAVA_COMET = 50,
  PRT_BEAST_PROJECTILE = 51,
  PRT_BEAST_BIG_PROJECTILE = 52,
  PRT_BEAST_DEBRIS = 53,
  PRT_BEAST_BIG_DEBRIS = 54,
  PRT_DEVIL_LASER = 55,
  PRT_DEVIL_ROCKET = 56,
  PRT_DEVIL_GUIDED_PROJECTILE = 57,
  PRT_GRUNT_PROJECTILE_SOL = 60,
  PRT_GRUNT_PROJECTILE_COM = 64,
  PRT_GUFFY_PROJECTILE = 61,
  PRT_DEMON_FIREBALL = 62,
  PRT_DEMON_FIREBALL_DEBRIS = 63,
  PRT_SHOOTER_WOODEN_DART = 70,
  PRT_SHOOTER_FIREBALL = 71,
  PRT_SHOOTER_FLAME = 72,
  PRT_LARVA_PLASMA = 73,
  PRT_LARVA_TAIL_PROJECTILE = 74,
  PRT_AIRELEMENTAL_WIND = 75,
  PRT_AFTERBURNER_DEBRIS = 76,
  PRT_METEOR = 77,
};
DECL_DLL inline void ClearToDefault(ProjectileType &e) { e = (ProjectileType)0; } ;
extern DECL_DLL CEntityPropertyEnumType ProjectileMovingType_enum;
enum ProjectileMovingType {
  PMT_FLYING = 0,
  PMT_SLIDING = 1,
  PMT_GUIDED = 2,
  PMT_GUIDED_FAST = 3,
  PMT_FLYING_REBOUNDING = 4,
  PMT_GUIDED_SLIDING = 5,
};
DECL_DLL inline void ClearToDefault(ProjectileMovingType &e) { e = (ProjectileMovingType)0; } ;
#define EVENTCODE_ELaunchProjectile 0x01f50000
class DECL_DLL ELaunchProjectile : public CEntityEvent {
public:
ELaunchProjectile();
CEntityEvent *MakeCopy(void);
CEntityPointer penLauncher;
enum ProjectileType prtType;
FLOAT fSpeed;
FLOAT fStretch;
};
DECL_DLL inline void ClearToDefault(ELaunchProjectile &e) { e = ELaunchProjectile(); } ;
extern "C" DECL_DLL CDLLEntityClass CProjectile_DLLClass;
class DECL_DLL  CProjectile : public CMovableModelEntity {
public:
virtual CEntity *GetPredictionPair(void) { return m_penPrediction; };
virtual void SetPredictionPair(CEntity *penPair) { m_penPrediction = penPair; };
   virtual void SetDefaultProperties(void);
  CEntityPointer m_penLauncher;
  enum ProjectileType m_prtType;
  enum ProjectileMovingType m_pmtMove;
  CEntityPointer m_penParticles;
  CEntityPointer m_penTarget;
  CEntityPointer m_penLastDamaged;
  FLOAT m_fSpeed;
  FLOAT m_fIgnoreTime;
  FLOAT m_fFlyTime;
  FLOAT m_fStartTime;
  FLOAT m_fDamageAmount;
  FLOAT m_fRangeDamageAmount;
  FLOAT m_fDamageHotSpotRange;
  FLOAT m_fDamageFallOffRange;
  FLOAT m_fSoundRange;
  BOOL m_bExplode;
  BOOL m_bLightSource;
  BOOL m_bCanHitHimself;
  BOOL m_bCanBeDestroyed;
  FLOAT m_fWaitAfterDeath;
  FLOAT m_aRotateSpeed;
  FLOAT m_tmExpandBox;
  FLOAT m_tmInvisibility;
  INDEX m_iRebounds;
  FLOAT m_fStretch;
  CSoundObject m_soEffect;
  CSoundObject m_soExplosion;
  FLOAT m_fGuidedMaxSpeedFactor;
  BOOL bLockedOn;
  BOOL m_bLeftFlame;
  CEntityPointer m_penPrediction;
CLightSource m_lsLightSource;
   
#line 585 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void PreMoving(void);
   
#line 596 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void PostMoving(void);
   
#line 611 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void Read_t(CTStream * istr);
   void DumpSync_t(CTStream & strm,INDEX iExtensiveSyncCheck);
   
#line 639 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
CLightSource * GetLightSource(void);
   void Copy(CEntity & enOther,ULONG ulFlags);
   
#line 659 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   
#line 677 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void SetupLightSource(BOOL bLive);
   
#line 809 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void RenderParticles(void);
   
#line 949 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void PlayerRocket(void);
   
#line 987 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void WalkerRocket(void);
   
#line 1022 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void WalkerRocketExplosion(void);
   
#line 1026 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void PlayerRocketExplosion(void);
   
#line 1070 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void PlayerGrenade(void);
   
#line 1103 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void PlayerGrenadeExplosion(void);
   
#line 1143 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void PlayerFlame(void);
   
#line 1179 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void PlayerLaserRay(void);
   
#line 1209 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void PlayerLaserWave(void);
   
#line 1232 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void CatmanProjectile(void);
   
#line 1259 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void HeadmanFirecracker(void);
   
#line 1283 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void HeadmanRocketman(void);
   
#line 1313 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void HeadmanBomberman(void);
   
#line 1339 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void HeadmanBombermanExplosion(void);
   
#line 1364 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void CyborgBombExplosion(void);
   
#line 1393 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void BonemanProjectile(void);
   
#line 1420 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void WomanProjectile(void);
   
#line 1447 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void DragonmanProjectile(INDEX iType);
   
#line 1483 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void ElementalRock(INDEX iSize,INDEX iType);
   
#line 1541 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void LavaManBomb(void);
   
#line 1603 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void LavamanBombExplosion(void);
   
#line 1677 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void LavamanBombDebrisExplosion(void);
   
#line 1719 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void HuanmanProjectile(void);
   
#line 1748 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void BeastProjectile(void);
   
#line 1783 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void BeastBigProjectile(void);
   
#line 1818 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void BeastDebris(void);
   
#line 1847 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void BeastBigDebris(void);
   
#line 1876 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void BeastDebrisExplosion(void);
   
#line 1899 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void BeastBigDebrisExplosion(void);
   
#line 1922 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void BeastProjectileExplosion(void);
   
#line 1980 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void BeastBigProjectileExplosion(void);
   
#line 2039 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void FishmanProjectile(void);
   
#line 2066 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void MantamanProjectile(void);
   
#line 2092 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void DevilLaser(void);
   
#line 2115 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void DevilRocket(void);
   
#line 2147 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void DevilRocketExplosion(void);
   
#line 2185 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void DevilGuidedProjectile(void);
   
#line 2219 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void DevilGuidedProjectileExplosion(void);
   
#line 2278 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void CyborgLaser(void);
   
#line 2300 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void CyborgBomb(void);
   
#line 2332 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void LavaBall(void);
   
#line 2358 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void LavaBallExplosion(void);
   
#line 2378 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void GruntSoldierLaser(void);
   
#line 2408 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void GruntCommanderLaser(void);
   
#line 2443 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void GuffyProjectile(void);
   
#line 2481 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void GuffyProjectileExplosion(void);
   
#line 2490 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void DemonFireball(void);
   
#line 2525 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void DemonFireballExplosion(void);
   
#line 2552 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void LarvaPlasma(void);
   
#line 2597 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void LarvaPlasmaExplosion(void);
   
#line 2619 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void LarvaTail(void);
   
#line 2654 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void LarvaTailExplosion(void);
   
#line 2663 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void WindBlast(void);
   
#line 2691 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void Meteor();
   
#line 2730 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void MeteorExplosion();
   
#line 2795 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void ShooterWoodenDart(void);
   
#line 2826 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void ShooterWoodenDartExplosion();
   
#line 2841 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void ShooterFireball(void);
   
#line 2874 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void ShooterFireballExplosion();
   
#line 2889 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void ShooterFlame(void);
   
#line 2910 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void AfterburnerDebris(void);
   
#line 2942 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void ProjectileTouch(CEntityPointer penHit);
   
#line 3013 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void ProjectileHit(void);
   
#line 3033 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void SpawnEffect(const CPlacement3D & plEffect,const ESpawnEffect & eSpawnEffect);
   
#line 3043 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void BounceSound(void);
   
#line 3057 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
ANGLE GetRotationSpeed(ANGLE aWantedAngle,ANGLE aRotateSpeed,FLOAT fWaitFrequency);
   
#line 3082 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 3083 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
#define  STATE_CProjectile_ProjectileFly 0x01f50001
  BOOL 
#line 3105 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
ProjectileFly(const CEntityEvent &__eeInput);
  BOOL H0x01f50002_ProjectileFly_01(const CEntityEvent &__eeInput);
  BOOL H0x01f50003_ProjectileFly_02(const CEntityEvent &__eeInput);
#define  STATE_CProjectile_ProjectileGuidedFly 0x01f50004
  BOOL 
#line 3167 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
ProjectileGuidedFly(const CEntityEvent &__eeInput);
  BOOL H0x01f50005_ProjectileGuidedFly_01(const CEntityEvent &__eeInput);
  BOOL H0x01f50006_ProjectileGuidedFly_02(const CEntityEvent &__eeInput);
  BOOL H0x01f50007_ProjectileGuidedFly_03(const CEntityEvent &__eeInput);
  BOOL H0x01f50008_ProjectileGuidedFly_04(const CEntityEvent &__eeInput);
#define  STATE_CProjectile_ProjectileGuidedFastFly 0x01f50009
  BOOL 
#line 3273 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
ProjectileGuidedFastFly(const CEntityEvent &__eeInput);
  BOOL H0x01f5000a_ProjectileGuidedFastFly_01(const CEntityEvent &__eeInput);
  BOOL H0x01f5000b_ProjectileGuidedFastFly_02(const CEntityEvent &__eeInput);
  BOOL H0x01f5000c_ProjectileGuidedFastFly_03(const CEntityEvent &__eeInput);
  BOOL H0x01f5000d_ProjectileGuidedFastFly_04(const CEntityEvent &__eeInput);
#define  STATE_CProjectile_ProjectileGuidedSlide 0x01f5000e
  BOOL 
#line 3406 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
ProjectileGuidedSlide(const CEntityEvent &__eeInput);
  BOOL H0x01f5000f_ProjectileGuidedSlide_01(const CEntityEvent &__eeInput);
  BOOL H0x01f50010_ProjectileGuidedSlide_02(const CEntityEvent &__eeInput);
  BOOL H0x01f50011_ProjectileGuidedSlide_03(const CEntityEvent &__eeInput);
  BOOL H0x01f50012_ProjectileGuidedSlide_04(const CEntityEvent &__eeInput);
#define  STATE_CProjectile_ProjectileSlide 0x01f50013
  BOOL 
#line 3498 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
ProjectileSlide(const CEntityEvent &__eeInput);
  BOOL H0x01f50014_ProjectileSlide_01(const CEntityEvent &__eeInput);
  BOOL H0x01f50015_ProjectileSlide_02(const CEntityEvent &__eeInput);
#define  STATE_CProjectile_ProjectileFlyRebounding 0x01f50016
  BOOL 
#line 3578 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
ProjectileFlyRebounding(const CEntityEvent &__eeInput);
  BOOL H0x01f50017_ProjectileFlyRebounding_01(const CEntityEvent &__eeInput);
  BOOL H0x01f50018_ProjectileFlyRebounding_02(const CEntityEvent &__eeInput);
#define  STATE_CProjectile_Main 1
  BOOL 
#line 3646 "C:/MyMod/Sources/EntitiesMP/Projectile.es"
Main(const CEntityEvent &__eeInput);
  BOOL H0x01f50019_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01f5001a_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x01f5001b_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x01f5001c_Main_04(const CEntityEvent &__eeInput);
  BOOL H0x01f5001d_Main_05(const CEntityEvent &__eeInput);
  BOOL H0x01f5001e_Main_06(const CEntityEvent &__eeInput);
  BOOL H0x01f5001f_Main_07(const CEntityEvent &__eeInput);
  BOOL H0x01f50020_Main_08(const CEntityEvent &__eeInput);
  BOOL H0x01f50021_Main_09(const CEntityEvent &__eeInput);
  BOOL H0x01f50022_Main_10(const CEntityEvent &__eeInput);
  BOOL H0x01f50023_Main_11(const CEntityEvent &__eeInput);
  BOOL H0x01f50024_Main_12(const CEntityEvent &__eeInput);
  BOOL H0x01f50025_Main_13(const CEntityEvent &__eeInput);
  BOOL H0x01f50026_Main_14(const CEntityEvent &__eeInput);
  BOOL H0x01f50027_Main_15(const CEntityEvent &__eeInput);
  BOOL H0x01f50028_Main_16(const CEntityEvent &__eeInput);
  BOOL H0x01f50029_Main_17(const CEntityEvent &__eeInput);
  BOOL H0x01f5002a_Main_18(const CEntityEvent &__eeInput);
  BOOL H0x01f5002b_Main_19(const CEntityEvent &__eeInput);
  BOOL H0x01f5002c_Main_20(const CEntityEvent &__eeInput);
  BOOL H0x01f5002d_Main_21(const CEntityEvent &__eeInput);
  BOOL H0x01f5002e_Main_22(const CEntityEvent &__eeInput);
  BOOL H0x01f5002f_Main_23(const CEntityEvent &__eeInput);
  BOOL H0x01f50030_Main_24(const CEntityEvent &__eeInput);
  BOOL H0x01f50031_Main_25(const CEntityEvent &__eeInput);
  BOOL H0x01f50032_Main_26(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_Projectile_INCLUDED
