/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_Scorpman_INCLUDED
#define _EntitiesMP_Scorpman_INCLUDED 1
#include <EntitiesMP/EnemyBase.h>
#include <EntitiesMP/Bullet.h>
#include <EntitiesMP/Reminder.h>
extern DECL_DLL CEntityPropertyEnumType ScorpmanType_enum;
enum ScorpmanType {
  SMT_SOLDIER = 0,
  SMT_GENERAL = 1,
  SMT_MONSTER = 2,
};
DECL_DLL inline void ClearToDefault(ScorpmanType &e) { e = (ScorpmanType)0; } ;
extern "C" DECL_DLL CDLLEntityClass CScorpman_DLLClass;
class CScorpman : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  enum ScorpmanType m_smtType;
  INDEX m_bFireBulletCount;
  INDEX m_iSpawnEffect;
  FLOAT m_fFireTime;
  CAnimObject m_aoLightAnimation;
  BOOL m_bSleeping;
CEntity * penBullet;
CLightSource m_lsLightSource;
  
#line 88 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
   
#line 98 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void Precache(void);
   
#line 110 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void Read_t(CTStream * istr);
   
#line 118 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
BOOL FillEntityStatistics(EntityStats * pes);
  
#line 129 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
virtual const CTFileName & GetComputerMessageName(void)const;
   
#line 142 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
CLightSource * GetLightSource(void);
   
#line 150 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
BOOL ForcesCannonballToExplode(void);
   
#line 159 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void SetupLightSource(void);
   
#line 174 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void PlayLightAnim(INDEX iAnim,ULONG ulFlags);
   
#line 181 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void MinigunOn(void);
   
#line 194 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void MinigunOff(void);
   
#line 203 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void * GetEntityInfo(void);
   
#line 214 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 215 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 225 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
INDEX AnimForDamage(FLOAT fDamage);
   
#line 239 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
INDEX AnimForDeath(void);
   
#line 245 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
FLOAT WaitForDust(FLOAT3D & vStretch);
   
#line 254 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void DeathNotify(void);
   
#line 260 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void StandingAnim(void);
   
#line 263 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void WalkingAnim(void);
   
#line 266 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void RunningAnim(void);
   
#line 269 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void RotatingAnim(void);
   
#line 274 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void IdleSound(void);
   
#line 277 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void SightSound(void);
   
#line 280 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void WoundSound(void);
   
#line 283 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void DeathSound(void);
   
#line 291 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
BOOL CanFireAtPlayer(void);
   
#line 322 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void PrepareBullet(FLOAT fDamage);
   
#line 346 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void FireBullet(void);
   
#line 361 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
void EnemyPostInit(void);
#define  STATE_CScorpman_Fire 0x01320000
  BOOL 
#line 372 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
Fire(const CEntityEvent &__eeInput);
  BOOL H0x01320001_Fire_01(const CEntityEvent &__eeInput);
  BOOL H0x01320002_Fire_02(const CEntityEvent &__eeInput);
  BOOL H0x01320003_Fire_03(const CEntityEvent &__eeInput);
  BOOL H0x01320004_Fire_04(const CEntityEvent &__eeInput);
  BOOL H0x01320005_Fire_05(const CEntityEvent &__eeInput);
  BOOL H0x01320006_Fire_06(const CEntityEvent &__eeInput);
  BOOL H0x01320007_Fire_07(const CEntityEvent &__eeInput);
  BOOL H0x01320008_Fire_08(const CEntityEvent &__eeInput);
#define  STATE_CScorpman_Hit 0x01320009
  BOOL 
#line 450 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
Hit(const CEntityEvent &__eeInput);
  BOOL H0x0132000a_Hit_01(const CEntityEvent &__eeInput);
  BOOL H0x0132000b_Hit_02(const CEntityEvent &__eeInput);
  BOOL H0x0132000c_Hit_03(const CEntityEvent &__eeInput);
  BOOL H0x0132000d_Hit_04(const CEntityEvent &__eeInput);
#define  STATE_CScorpman_Sleep 0x0132000e
  BOOL 
#line 471 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
Sleep(const CEntityEvent &__eeInput);
  BOOL H0x0132000f_Sleep_01(const CEntityEvent &__eeInput);
  BOOL H0x01320010_Sleep_02(const CEntityEvent &__eeInput);
#define  STATE_CScorpman_WakeUp 0x01320011
  BOOL 
#line 495 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
WakeUp(const CEntityEvent &__eeInput);
  BOOL H0x01320012_WakeUp_01(const CEntityEvent &__eeInput);
  BOOL H0x01320013_WakeUp_02(const CEntityEvent &__eeInput);
#define  STATE_CScorpman_PreMainLoop 0x01320014
  BOOL 
#line 509 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
PreMainLoop(const CEntityEvent &__eeInput);
  BOOL H0x01320015_PreMainLoop_01(const CEntityEvent &__eeInput);
  BOOL H0x01320016_PreMainLoop_02(const CEntityEvent &__eeInput);
  BOOL H0x01320017_PreMainLoop_03(const CEntityEvent &__eeInput);
#define  STATE_CScorpman_Main 1
  BOOL 
#line 535 "C:/MyMod/Sources/EntitiesMP/Scorpman.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_Scorpman_INCLUDED
