/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/MyMod/Sources/EntitiesMP/StormController.es"

#include "StdH.h"
#include "EntitiesMP/BackgroundViewer.h"
#include "EntitiesMP/WorldSettingsController.h"
#include "EntitiesMP/Lightning.h"

#include <EntitiesMP/StormController.h>
#include <EntitiesMP/StormController_tables.h>
void CStormController::SetDefaultProperties(void) {
  m_penwsc = NULL;
  m_strName = "Storm controller";
  m_fNextLightningDelay = 0.0f;
  m_bStormOn = FALSE ;
  m_fNextLightningStrike = 0.0f;
  m_penLightning00 = NULL;
  m_penLightning01 = NULL;
  m_penLightning02 = NULL;
  m_penLightning03 = NULL;
  m_penLightning04 = NULL;
  m_penLightning05 = NULL;
  m_penLightning06 = NULL;
  m_penLightning07 = NULL;
  m_penLightning08 = NULL;
  m_penLightning09 = NULL;
  m_penLightning10 = NULL;
  m_penLightning11 = NULL;
  m_penLightning12 = NULL;
  m_penLightning13 = NULL;
  m_penLightning14 = NULL;
  m_penLightning15 = NULL;
  m_penLightning16 = NULL;
  m_penLightning17 = NULL;
  m_penLightning18 = NULL;
  m_penLightning19 = NULL;
  m_tmStormAppearTime = 10.0f;
  m_tmStormDisappearTime = 10.0f;
  m_fFirstLightningDelay = 10.0f;
  m_fMaxLightningPeriod = 10.0f;
  m_fMinLightningPeriod = 1.0f;
  m_fMaxStormPowerTime = 120.0f;
  m_colBlendStart = COLOR(C_WHITE  | CT_TRANSPARENT );
  m_colBlendStop = COLOR(C_WHITE  | CT_OPAQUE );
  m_colShadeStart = COLOR(C_WHITE  | CT_OPAQUE );
  m_colShadeStop = COLOR(C_GRAY  | CT_OPAQUE );
  CRationalEntity::SetDefaultProperties();
}
  
#line 59 "C:/MyMod/Sources/EntitiesMP/StormController.es"
void CStormController::CheckOneLightningTarget(CEntityPointer & pen) 
#line 60 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 61 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(pen  != NULL  && ! IsOfClass  (pen  , "Lightning"))
#line 62 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 63 "C:/MyMod/Sources/EntitiesMP/StormController.es"
WarningMessage  ("Target '%s' is not of class Lightning!" , pen  -> GetName  ());
#line 64 "C:/MyMod/Sources/EntitiesMP/StormController.es"
pen  = NULL ;
#line 65 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
#line 66 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
  
#line 69 "C:/MyMod/Sources/EntitiesMP/StormController.es"
INDEX CStormController::GetLightningsCount(void)const 
#line 70 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 72 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning00  == NULL ){return 0;};
#line 73 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning01  == NULL ){return 1;};
#line 74 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning02  == NULL ){return 2;};
#line 75 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning03  == NULL ){return 3;};
#line 76 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning04  == NULL ){return 4;};
#line 77 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning05  == NULL ){return 5;};
#line 78 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning06  == NULL ){return 6;};
#line 79 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning07  == NULL ){return 7;};
#line 80 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning08  == NULL ){return 8;};
#line 81 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning09  == NULL ){return 9;};
#line 82 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning10  == NULL ){return 10;};
#line 83 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning11  == NULL ){return 11;};
#line 84 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning12  == NULL ){return 12;};
#line 85 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning13  == NULL ){return 13;};
#line 86 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning14  == NULL ){return 14;};
#line 87 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning15  == NULL ){return 15;};
#line 88 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning16  == NULL ){return 16;};
#line 89 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning17  == NULL ){return 17;};
#line 90 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penLightning18  == NULL ){return 18;};
#line 91 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return 20;
#line 92 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
BOOL CStormController::
#line 95 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Storm(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CStormController_Storm
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CStormController::Storm expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 98 "C:/MyMod/Sources/EntitiesMP/StormController.es"
SetTimerAfter(10.0f);
Jump(STATE_CURRENT, 0x025e0001, FALSE, EBegin());return TRUE;}BOOL CStormController::H0x025e0001_Storm_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e0001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x025e0002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CStormController::H0x025e0002_Storm_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e0002
;
#line 99 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_fNextLightningStrike  = m_tmStormAppearTime  + m_fFirstLightningDelay ;
#line 100 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Jump(STATE_CURRENT, STATE_CStormController_StormInternal, TRUE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CStormController::
#line 103 "C:/MyMod/Sources/EntitiesMP/StormController.es"
StormInternal(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CStormController_StormInternal
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CStormController::StormInternal expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 105 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Jump(STATE_CURRENT,0x025e000a, FALSE, EInternal());return TRUE;}BOOL CStormController::H0x025e000a_StormInternal_07(const CEntityEvent &__eeInput)
#line 107 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e000a
if(!(m_bStormOn  && 
#line 106 "C:/MyMod/Sources/EntitiesMP/StormController.es"
_pTimer  -> CurrentTick  () < ((CWorldSettingsController  *) & * m_penwsc ) -> m_tmStormEnd  + m_tmStormDisappearTime )){ Jump(STATE_CURRENT,0x025e000b, FALSE, EInternal());return TRUE;}
#line 108 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Jump(STATE_CURRENT,0x025e0006, FALSE, EInternal());return TRUE;}BOOL CStormController::H0x025e0006_StormInternal_03(const CEntityEvent &__eeInput)
#line 111 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e0006
if(!(_pTimer  -> CurrentTick  () < m_fNextLightningStrike  && 
#line 109 "C:/MyMod/Sources/EntitiesMP/StormController.es"
_pTimer  -> CurrentTick  () < ((CWorldSettingsController  *) & * m_penwsc ) -> m_tmStormEnd  + m_tmStormDisappearTime  && 
#line 110 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_bStormOn )){ Jump(STATE_CURRENT,0x025e0007, FALSE, EInternal());return TRUE;}
#line 113 "C:/MyMod/Sources/EntitiesMP/StormController.es"
SetTimerAfter(_pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x025e0004, FALSE, EBegin());return TRUE;}BOOL CStormController::H0x025e0004_StormInternal_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e0004
switch(__eeInput.ee_slEvent)
#line 114 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{case(EVENTCODE_EBegin):
#line 116 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{const EBegin&e= (EBegin&)__eeInput;

#line 117 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return TRUE;
#line 118 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}ASSERT(FALSE);break;case(EVENTCODE_EEnvironmentStop):
#line 120 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{const EEnvironmentStop&e= (EEnvironmentStop&)__eeInput;

#line 121 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_fNextLightningStrike  += 1.0f;
#line 122 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return TRUE;
#line 123 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x025e0005, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 125 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}return TRUE;}BOOL CStormController::H0x025e0005_StormInternal_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e0005
Jump(STATE_CURRENT,0x025e0006, FALSE, EInternal());return TRUE;
#line 126 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}BOOL CStormController::H0x025e0007_StormInternal_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e0007

#line 127 "C:/MyMod/Sources/EntitiesMP/StormController.es"
SetTimerAfter(_pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x025e0008, FALSE, EBegin());return TRUE;}BOOL CStormController::H0x025e0008_StormInternal_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e0008
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x025e0009, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CStormController::H0x025e0009_StormInternal_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e0009
;
#line 130 "C:/MyMod/Sources/EntitiesMP/StormController.es"
FLOAT fLightningStart  = ((CWorldSettingsController  *) & * m_penwsc ) -> m_tmStormStart  + m_fFirstLightningDelay ;
#line 131 "C:/MyMod/Sources/EntitiesMP/StormController.es"
FLOAT fLightningMax  = fLightningStart  + m_fMaxStormPowerTime ;
#line 132 "C:/MyMod/Sources/EntitiesMP/StormController.es"
FLOAT fRatio ;
#line 134 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(_pTimer  -> CurrentTick  () > ((CWorldSettingsController  *) & * m_penwsc ) -> m_tmStormEnd  - m_tmStormDisappearTime )
#line 135 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 136 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_bStormOn  = FALSE ;
#line 137 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
#line 138 "C:/MyMod/Sources/EntitiesMP/StormController.es"
else 
#line 139 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 141 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(_pTimer  -> CurrentTick  () < fLightningMax )
#line 142 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 143 "C:/MyMod/Sources/EntitiesMP/StormController.es"
fRatio  = CalculateRatio  (_pTimer  -> CurrentTick  () , fLightningStart  , fLightningMax  , 1.0f , 0.0f);
#line 144 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
#line 146 "C:/MyMod/Sources/EntitiesMP/StormController.es"
else 
#line 147 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 148 "C:/MyMod/Sources/EntitiesMP/StormController.es"
fRatio  = 1;
#line 149 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
#line 150 "C:/MyMod/Sources/EntitiesMP/StormController.es"
FLOAT tmPeriod  = (m_fMaxLightningPeriod  - m_fMinLightningPeriod ) * (1.0f - fRatio );
#line 151 "C:/MyMod/Sources/EntitiesMP/StormController.es"
FLOAT fNextLighting  = m_fMinLightningPeriod  + tmPeriod  * (1.0f + (FRnd  () - 0.5f) * 0.25f);
#line 152 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_fNextLightningStrike  = _pTimer  -> CurrentTick  () + fNextLighting ;
#line 155 "C:/MyMod/Sources/EntitiesMP/StormController.es"
INDEX ctLightnings  = GetLightningsCount  ();
#line 157 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(ctLightnings  != 0)
#line 158 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 160 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CLightning  * penLightning  = (CLightning  *) & * (& m_penLightning00 ) [ IRnd  () % ctLightnings  ];
#line 161 "C:/MyMod/Sources/EntitiesMP/StormController.es"
SendToTarget  (penLightning  , EET_TRIGGER );
#line 162 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
#line 163 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}Jump(STATE_CURRENT,0x025e000a, FALSE, EInternal());return TRUE;
#line 164 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}BOOL CStormController::H0x025e000b_StormInternal_08(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e000b

#line 165 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_bStormOn  = FALSE ;
#line 166 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Return(STATE_CURRENT,EReturn  ());
#line 166 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CStormController::
#line 169 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CStormController_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CStormController::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 172 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning00 );
#line 173 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning01 );
#line 174 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning02 );
#line 175 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning03 );
#line 176 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning04 );
#line 177 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning05 );
#line 178 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning06 );
#line 179 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning07 );
#line 180 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning08 );
#line 181 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning09 );
#line 182 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning10 );
#line 183 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning11 );
#line 184 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning12 );
#line 185 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning13 );
#line 186 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning14 );
#line 187 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning15 );
#line 188 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning16 );
#line 189 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning17 );
#line 190 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning18 );
#line 191 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CheckOneLightningTarget  (m_penLightning19 );
#line 194 "C:/MyMod/Sources/EntitiesMP/StormController.es"
InitAsEditorModel  ();
#line 195 "C:/MyMod/Sources/EntitiesMP/StormController.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 196 "C:/MyMod/Sources/EntitiesMP/StormController.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 199 "C:/MyMod/Sources/EntitiesMP/StormController.es"
SetModel  (MODEL_STORM_CONTROLLER );
#line 200 "C:/MyMod/Sources/EntitiesMP/StormController.es"
SetModelMainTexture  (TEXTURE_STORM_CONTROLLER );
#line 203 "C:/MyMod/Sources/EntitiesMP/StormController.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x025e000c, FALSE, EBegin());return TRUE;}BOOL CStormController::H0x025e000c_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e000c
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x025e000d, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CStormController::H0x025e000d_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e000d
;
#line 206 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CBackgroundViewer  * penBcgViewer  = (CBackgroundViewer  *) GetWorld  () -> GetBackgroundViewer  ();
#line 207 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(penBcgViewer  == NULL )
#line 208 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 210 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Return(STATE_CURRENT,EVoid());
#line 210 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return TRUE;
#line 211 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
#line 214 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_penwsc  = penBcgViewer  -> m_penWorldSettingsController ;
#line 215 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_penwsc  == NULL )
#line 216 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 218 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Return(STATE_CURRENT,EVoid());
#line 218 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return TRUE;
#line 219 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
#line 222 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(! IsOfClass  (m_penwsc  , "WorldSettingsController"))
#line 223 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 225 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Return(STATE_CURRENT,EVoid());
#line 225 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return TRUE;
#line 226 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
#line 228 "C:/MyMod/Sources/EntitiesMP/StormController.es"
CWorldSettingsController  * pwsc  = (CWorldSettingsController  *) & * m_penwsc ;
#line 229 "C:/MyMod/Sources/EntitiesMP/StormController.es"
pwsc  -> m_colBlendStart  = m_colBlendStart ;
#line 230 "C:/MyMod/Sources/EntitiesMP/StormController.es"
pwsc  -> m_colBlendStop  = m_colBlendStop ;
#line 231 "C:/MyMod/Sources/EntitiesMP/StormController.es"
pwsc  -> m_colShadeStart  = m_colShadeStart ;
#line 232 "C:/MyMod/Sources/EntitiesMP/StormController.es"
pwsc  -> m_colShadeStop  = m_colShadeStop ;
#line 233 "C:/MyMod/Sources/EntitiesMP/StormController.es"
pwsc  -> m_tmStormAppearTime  = m_tmStormAppearTime ;
#line 234 "C:/MyMod/Sources/EntitiesMP/StormController.es"
pwsc  -> m_tmStormDisappearTime  = m_tmStormDisappearTime ;
#line 236 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_bStormOn  = FALSE ;
#line 237 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Jump(STATE_CURRENT,0x025e0010, FALSE, EInternal());return TRUE;}BOOL CStormController::H0x025e0010_Main_05(const CEntityEvent &__eeInput)
#line 238 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e0010
if(!(TRUE )){ Jump(STATE_CURRENT,0x025e0011, FALSE, EInternal());return TRUE;}
#line 239 "C:/MyMod/Sources/EntitiesMP/StormController.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x025e000e, FALSE, EBegin());return TRUE;}BOOL CStormController::H0x025e000e_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e000e
switch(__eeInput.ee_slEvent)
#line 240 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{case(EVENTCODE_EEnvironmentStart):
#line 243 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{const EEnvironmentStart&eEnvironmentStart= (EEnvironmentStart&)__eeInput;

#line 244 "C:/MyMod/Sources/EntitiesMP/StormController.es"
TIME  tmNow  = _pTimer  -> CurrentTick  ();
#line 245 "C:/MyMod/Sources/EntitiesMP/StormController.es"
((CWorldSettingsController  *) & * m_penwsc ) -> m_tmStormStart  = tmNow  - m_tmStormAppearTime ;
#line 246 "C:/MyMod/Sources/EntitiesMP/StormController.es"
((CWorldSettingsController  *) & * m_penwsc ) -> m_tmStormEnd  = 1e6;
#line 247 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_bStormOn  = TRUE ;
#line 248 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_fNextLightningStrike  = _pTimer  -> CurrentTick  () + 2.0f;
#line 249 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Call(STATE_CURRENT, STATE_CStormController_StormInternal, TRUE, EVoid());return TRUE;
#line 250 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return TRUE;
#line 251 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):
#line 253 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{const EStart&eStart= (EStart&)__eeInput;

#line 254 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(! m_bStormOn )
#line 255 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 256 "C:/MyMod/Sources/EntitiesMP/StormController.es"
TIME  tmNow  = _pTimer  -> CurrentTick  ();
#line 257 "C:/MyMod/Sources/EntitiesMP/StormController.es"
((CWorldSettingsController  *) & * m_penwsc ) -> m_tmStormStart  = tmNow ;
#line 258 "C:/MyMod/Sources/EntitiesMP/StormController.es"
((CWorldSettingsController  *) & * m_penwsc ) -> m_tmStormEnd  = 1e6;
#line 259 "C:/MyMod/Sources/EntitiesMP/StormController.es"
m_bStormOn  = TRUE ;
#line 260 "C:/MyMod/Sources/EntitiesMP/StormController.es"
Call(STATE_CURRENT, STATE_CStormController_Storm, TRUE, EVoid());return TRUE;
#line 261 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
#line 262 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return TRUE;
#line 263 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):
#line 265 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{const EStop&eStop= (EStop&)__eeInput;

#line 266 "C:/MyMod/Sources/EntitiesMP/StormController.es"
if(m_bStormOn )
#line 267 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 268 "C:/MyMod/Sources/EntitiesMP/StormController.es"
TIME  tmNow  = _pTimer  -> CurrentTick  ();
#line 269 "C:/MyMod/Sources/EntitiesMP/StormController.es"
((CWorldSettingsController  *) & * m_penwsc ) -> m_tmStormEnd  = tmNow ;
#line 270 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}
#line 271 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return TRUE;
#line 272 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}ASSERT(FALSE);break;default:
#line 274 "C:/MyMod/Sources/EntitiesMP/StormController.es"
{
#line 275 "C:/MyMod/Sources/EntitiesMP/StormController.es"
return TRUE;
#line 276 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}ASSERT(FALSE);break;
#line 277 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}return TRUE;}BOOL CStormController::H0x025e000f_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e000f
;Jump(STATE_CURRENT,0x025e0010, FALSE, EInternal());return TRUE;
#line 278 "C:/MyMod/Sources/EntitiesMP/StormController.es"
}BOOL CStormController::H0x025e0011_Main_06(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025e0011
 ASSERT(FALSE); return TRUE;};